name = "TextlayoutJosephsonCircuits"
uuid = "a1aa9a1d-e3af-42c9-a2d1-5fb1fddc6a6e"
authors = ["Text-to-GDS contributors"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-fb0d68bcfaf4"
JosephsonCircuits = "23a5dba6-321f-4fcf-be1e-689e290df087"

[compat]
JSON3 = "1"
JosephsonCircuits = "0.5.2"
julia = "1.10"
