from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from text_to_gds.backends.base import Backend, BackendAvailability, python_module_available


class GDSFactoryBackend(Backend):
    name = "gdsfactory"
    role = "general GDS manipulation backend"
    source_url = "https://github.com/gdsfactory/gdsfactory"

    _DEVICE_LIBRARY_NAMES = {
        "transmon",
        "qubit",
        "jpa",
        "jtwpa",
        "squid",
        "junction",
        "resonator",
        "cpw_resonator",
        "cpw_quarter_wave_resonator",
    }

    def available(self) -> BackendAvailability:
        if python_module_available("gdsfactory"):
            return BackendAvailability(True, "Python module gdsfactory is importable")
        return BackendAvailability(False, "gdsfactory is not installed")

    def generate(self, request: dict[str, Any], *, output_dir: str | Path) -> dict[str, Any]:
        device = str(request.get("device") or "").lower()
        if device in self._DEVICE_LIBRARY_NAMES:
            return self._status(
                "UNSUPPORTED",
                operation="generate",
                reason=(
                    "gdsfactory is reserved for GDS manipulation/routing glue; "
                    f"{device!r} must be generated by KQCircuits or Qiskit Metal"
                ),
                output_dir=output_dir,
                extra={"request": request},
            )
        if not self.available().available:
            return self._status(
                "SKIPPED",
                operation="generate",
                reason="gdsfactory runtime unavailable",
                output_dir=output_dir,
                extra={"request": request},
            )

        import gdsfactory as gf

        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        gds_path = out / f"{device or 'gdsfactory_component'}.gds"
        metadata_path = out / f"{device or 'gdsfactory_component'}_metadata.json"

        component = gf.Component(device or "gdsfactory_component")
        for rectangle in request.get("rectangles", []):
            size = tuple(rectangle.get("size", (10.0, 10.0)))
            layer = tuple(rectangle.get("layer", (1, 0)))
            ref = component << gf.components.rectangle(size=size, layer=layer)
            ref.move(tuple(rectangle.get("origin", (0.0, 0.0))))
        if not component.insts:
            return self._status(
                "UNSUPPORTED",
                operation="generate",
                reason="gdsfactory request contains no generic GDS operations",
                output_dir=out,
                extra={"request": request},
            )

        component.write_gds(gds_path)
        metadata_path.write_text(
            json.dumps(
                {
                    "schema": "text-to-gds.gdsfactory-metadata.v1",
                    "backend": self.name,
                    "device": device,
                    "operations": request.get("rectangles", []),
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        return self._status(
            "EXECUTED",
            operation="generate",
            reason="Generated generic GDS glue with gdsfactory",
            output_dir=out,
            artifacts={"gds": str(gds_path), "metadata": str(metadata_path)},
            extra={"request": request},
        )
