"""Honest input preparation for openEMS and FastHenry benchmarks."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from textlayout.models import Geometry, Technology
from textlayout.schemas.dsl import LayoutSpec
from textlayout.simulation.models import SimulationResult


def prepare_cpw_openems(
    spec: LayoutSpec, geometry: Geometry, technology: Technology, output_dir: str | Path
) -> SimulationResult:
    return _prepare_openems(
        spec,
        geometry,
        technology,
        output_dir,
        expected=("Z0", "S11", "S21", "effective_permittivity"),
    )


def prepare_resonator_openems(
    spec: LayoutSpec, geometry: Geometry, technology: Technology, output_dir: str | Path
) -> SimulationResult:
    return _prepare_openems(
        spec,
        geometry,
        technology,
        output_dir,
        expected=("resonance_frequency", "loaded_Q", "S21"),
    )


def _prepare_openems(
    spec: LayoutSpec,
    geometry: Geometry,
    technology: Technology,
    output_dir: str | Path,
    *,
    expected: tuple[str, ...],
) -> SimulationResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    config = out / "openems_model.json"
    driver = out / "openems_model.m"
    bbox = geometry.bbox()
    payload = {
        "status": "input_files_prepared",
        "solver": "openEMS",
        "component": spec.component,
        "target": dict(spec.target),
        "technology": technology.name,
        "substrate_epsilon_r": technology.substrate_epsilon_r,
        "bbox_um": [bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax],
        "ports": [
            {
                "name": port.name,
                "center_um": list(port.center),
                "width_um": port.width,
                "orientation_deg": port.orientation,
                "layer": port.layer,
            }
            for port in geometry.ports
        ],
        "expected_outputs": list(expected),
        "execution": "not_run",
        "driver": driver.name,
    }
    config.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    driver.write_text(_render_openems_octave(spec, geometry, technology), encoding="utf-8")
    warnings = (
        "The Octave driver is runnable only with the external openEMS/CSXCAD stack installed.",
        "Boundary placement and mesh convergence must be reviewed before signoff.",
    )
    # No host-solver discovery is written into these artifacts. They are
    # committed to the repository and describe *prepared inputs*
    # (execution="not_run"), so the absolute path of whichever openEMS binary
    # happens to sit on the generating machine is not evidence about the
    # design -- it is evidence about the machine. Embedding it made the
    # artifacts non-reproducible (the CI determinism gate fails for anyone who
    # has openEMS installed) and leaked local usernames into committed JSON.
    # Host capability belongs in `textlayout doctor`; solver identity and
    # version belong in the evidence record of a run that actually executed.
    manifest = _write_manifest(out, "openEMS", spec.component, expected, warnings)
    return SimulationResult(
        status="input_files_prepared",
        solver="openEMS",
        readiness_level=2,
        reason="A runnable openEMS/CSXCAD Octave model and manifest were generated.",
        output_dir=out,
        artifacts={"model": str(config), "driver": str(driver), "manifest": str(manifest)},
        warnings=warnings,
    )


def _render_openems_octave(spec: LayoutSpec, geometry: Geometry, technology: Technology) -> str:
    """Render a self-contained openEMS Octave driver from verified polygons.

    The port call deliberately uses openEMS' native ``AddCPWPort`` API for a
    straight CPW.  Resonators use calibrated lumped ports on the feedline,
    because a hanger is not itself a through CPW-port cross-section.
    """
    if spec.component == "CPW":
        return _render_cpw_openems_octave(spec, technology)
    bbox = geometry.bbox()
    margin = min(max(bbox.width, bbox.height) * 0.05 + 20.0, 200.0)
    f0 = float(spec.target.get("frequency_ghz", 6.0)) * 1e9
    f_start = max(1e6, f0 * 0.5)
    f_stop = f0 * 1.5
    substrate_h = 200.0
    interface_lines = _openems_octave_bootstrap_lines()
    lines = [
        "% Generated by textlayout; units are micrometres.",
        "close all; clear; clc;",
        *interface_lines,
        "physical_constants;",
        "unit = 1e-6;",
        f"f_start = {f_start:.12g}; f_stop = {f_stop:.12g};",
        # Micron-scale cells force a femtosecond timestep; a high-Q hanger
        # additionally needs many ring-down time constants, so a converged
        # resonator run is inherently hours long. The runner's convergence
        # gate keeps a truncated run honest (FAILED, no numbers) rather than
        # letting a broadened/edge resonance masquerade as evidence.
        "FDTD = InitFDTD('NrTS', 1500000, 'EndCriteria', 1e-6);",
        "FDTD = SetGaussExcite(FDTD, (f_start+f_stop)/2, (f_stop-f_start)/2);",
        "FDTD = SetBoundaryCond(FDTD, {'PML_8','PML_8','PML_8','PML_8','PML_8','PML_8'});",
        "CSX = InitCSX();",
        # AddMaterial's varargin sets generic property attributes, NOT the
        # material constants — Epsilon passed there is silently ignored and
        # the "substrate" simulates as vacuum. SetMaterialProperty is the
        # only call the engine reads (root cause of air-like Z0/eps_eff).
        "CSX = AddMaterial(CSX, 'substrate');",
        f"CSX = SetMaterialProperty(CSX, 'substrate', 'Epsilon', {technology.substrate_epsilon_r:.12g});",
        (
            "CSX = AddBox(CSX, 'substrate', 0, "
            f"[{bbox.xmin - margin:.9g} {bbox.ymin - margin:.9g} {-substrate_h:.9g}], "
            f"[{bbox.xmax + margin:.9g} {bbox.ymax + margin:.9g} 0]);"
        ),
        "CSX = AddMetal(CSX, 'metal');",
    ]
    for index, polygon in enumerate(geometry.polygons):
        if polygon.layer != str(spec.parameters.get("metal", "M1")):
            continue
        xs = " ".join(f"{point[0]:.9g}" for point in polygon.points)
        ys = " ".join(f"{point[1]:.9g}" for point in polygon.points)
        lines.extend(
            (
                f"p{index} = [{xs}; {ys}];",
                f"CSX = AddPolygon(CSX, 'metal', 10, 'z', 0, p{index});",
            )
        )
    width = float(spec.parameters["center_width_um"])
    gap = float(spec.parameters["gap_um"])
    edge_res = max(0.5, min(gap / 3.0, width / 4.0))
    # A lumped/gap port that does not lie exactly on grid lines rasterizes to
    # nothing: the excitation injects ZERO energy for the whole run and every
    # S-parameter becomes 0/0 = NaN (observed: a 250k-timestep run with
    # "Energy: ~0.00e+00" throughout). Collect the port coordinates BEFORE
    # DefineRectGrid and force mesh lines through them.
    port_positions = [port.center for port in geometry.ports[:2]]
    # Local fine lines only — a fine SmoothMeshLines interval spanning between
    # two distant ports would explode the cell count by orders of magnitude.
    fine_x = sorted(
        {
            round(coord, 6)
            for x, _ in port_positions
            for coord in (x - edge_res, x, x + edge_res)
        }
    )
    fine_y = sorted(
        {
            round(coord, 6)
            for _, y in port_positions
            for base in (y + width / 2, y + width / 2 + gap)
            for coord in (base - edge_res, base, base + edge_res)
        }
    )
    port_x = " ".join(f"{value:.9g}" for value in fine_x)
    port_y = " ".join(f"{value:.9g}" for value in fine_y)
    lines.extend(
        (
            (
                "mesh.x = SmoothMeshLines(["
                f"{bbox.xmin - margin:.9g} {port_x} {bbox.xmax + margin:.9g}], 20, 1.4);"
            ),
            (
                "mesh.y = SmoothMeshLines(["
                f"{bbox.ymin - margin:.9g} {port_y} {bbox.ymax + margin:.9g}], 20, 1.4);"
            ),
            # Resolve z finely at the metal plane (z=0) where the CPW gap
            # fields live; coarsen into the substrate and the air above.
            f"mesh.z = SmoothMeshLines([{-3*gap:.9g} 0 {3*gap:.9g}], {edge_res:.9g}, 1.3, 0);",
            f"mesh.z = SmoothMeshLines([{-substrate_h:.9g} mesh.z 100], 20, 1.4);",
            "CSX = DefineRectGrid(CSX, unit, mesh);",
        )
    )
    # Feedline-to-upper-ground gap ports for the hanger; the first is excited.
    for number, port in enumerate(geometry.ports[:2], 1):
        x, y = port.center
        excite = 1 if number == 1 else 0
        lines.append(
            f"[CSX, port{{{number}}}] = AddLumpedPort(CSX, 999, {number}, 50, "
            f"[{x:.9g} {y + width / 2:.9g} 0], "
            f"[{x:.9g} {y + width / 2 + gap:.9g} 0], "
            f"[0 1 0], {excite});"
        )
    lines.extend(
        (
            "Sim_Path = 'openems_run'; Sim_CSX = 'model.xml';",
            "[status, message] = rmdir(Sim_Path, 's'); mkdir(Sim_Path);",
            "WriteOpenEMS(fullfile(Sim_Path, Sim_CSX), FDTD, CSX);",
            "RunOpenEMS(Sim_Path, Sim_CSX);",
            "freq = linspace(f_start, f_stop, 401);",
            "port = calcPort(port, Sim_Path, freq);",
            "s11 = port{1}.uf.ref ./ port{1}.uf.inc;",
            "s21 = port{2}.uf.ref ./ port{1}.uf.inc;",
            "fid = fopen('openems_result.s2p', 'w');",
            "fprintf(fid, '# Hz S RI R 50\\n');",
            "for k=1:numel(freq)",
            "  fprintf(fid, '%.12e %.12e %.12e %.12e %.12e %.12e %.12e %.12e %.12e\\n', freq(k), real(s11(k)), imag(s11(k)), real(s21(k)), imag(s21(k)), real(s21(k)), imag(s21(k)), real(s11(k)), imag(s11(k)));",
            "end",
            "fclose(fid);",
        )
    )
    return "\n".join(lines) + "\n"


def _openems_octave_bootstrap_lines() -> list[str]:
    from textlayout.simulation.runners import discover_openems_stack

    stack = discover_openems_stack()
    lines: list[str] = []
    for key in ("octave_openems_path", "octave_csxcad_path"):
        value = stack.get(key)
        if value:
            lines.append(f"addpath('{value.removeprefix('wsl:')}');")
    core = stack.get("openems")
    if core and core.startswith("wsl:"):
        binary_dir = str(Path(core.removeprefix("wsl:")).parent).replace("\\", "/")
        prefix = str(Path(binary_dir).parent).replace("\\", "/")
        lines.extend(
            (
                f"setenv('PATH', ['{binary_dir}' pathsep getenv('PATH')]);",
                f"setenv('LD_LIBRARY_PATH', ['{prefix}/lib' pathsep '{prefix}/lib64' pathsep getenv('LD_LIBRARY_PATH')]);",
            )
        )
    return lines


def _render_cpw_openems_octave(spec: LayoutSpec, technology: Technology) -> str:
    """Render a finite, terminated CPW model following the official openEMS example."""
    length = float(spec.parameters["length_um"])
    width = float(spec.parameters["center_width_um"])
    gap = float(spec.parameters["gap_um"])
    ground = float(spec.parameters.get("ground_width_um", 50.0))
    substrate_h = 500.0
    # A CPW analysis assumes quasi-infinite grounds: keep at least ~10 full
    # cross-sections of ground+substrate on each side, whatever the drawn
    # ground width is (a 122 um-wide substrate ribbon under 50 um grounds
    # measurably shifted both eps_eff and Z0).
    substrate_width = max(2.0 * (ground + gap + width / 2.0), 20.0 * (width + 2.0 * gap))
    port_length = min(max(length * 0.2, 100.0), length * 0.4)
    f0 = float(spec.target.get("frequency_ghz", 6.0)) * 1e9
    # Micron-scale cells force a femtosecond FDTD timestep, so the Gaussian
    # source pulse spans hundreds of thousands of timesteps: keep the band
    # wide (short pulse). But do NOT excite down to DC — MUR boundaries and
    # the feed resistors never drain the static charge a near-DC pulse
    # deposits, leaving a permanent energy plateau in the domain.
    f_start = f0 / 4.0
    f_stop = 2.0 * f0
    edge_res = max(0.5, min(gap / 3.0, width / 4.0))
    coarse_res = max(10.0, min(40.0, length / 20.0))
    half = length / 2.0
    # Absorbing-boundary clearance and the coarse cell size in the air region
    # scale with wavelength, not with the (micron-scale) line cross-section.
    air = 2000.0
    air_res = 300.0
    third = edge_res / 3.0
    lines = [
        "% Generated by textlayout from the official openEMS finite CPW pattern",
        "% (matlab/examples/transmission_lines/CPW_Line.m).",
        "close all; clear; clc;",
        *_openems_octave_bootstrap_lines(),
        "physical_constants; unit = 1e-6;",
        f"f_start = {f_start:.12g}; f_stop = {f_stop:.12g};",
        # EndCriteria 1e-6 (-60 dB): with a femtosecond timestep the domain
        # energy tracks the source envelope, so a looser criterion trips on
        # the Gaussian tail while meaningful source amplitude remains. The
        # runner additionally refuses to extract numbers when the run covered
        # less than 90% of the excitation support or ended by NrTS with the
        # energy still high (truncated DFT = garbage S either way).
        "FDTD = InitFDTD('NrTS', 1500000, 'EndCriteria', 1e-6);",
        "FDTD = SetGaussExcite(FDTD, (f_start+f_stop)/2, (f_stop-f_start)/2);",
        "FDTD = SetBoundaryCond(FDTD, [2 2 2 2 2 2]);",
        "CSX = InitCSX();",
        f"mesh.x = SmoothMeshLines([-{half:.9g} 0 {half:.9g}], {coarse_res:.9g}, 1.4, 0);",
        f"mesh.x = SmoothMeshLines([-{half + air:.9g} mesh.x {half + air:.9g}], {air_res:.9g}, 1.4, 0);",
        # Thirds rule at the four metal edges (1/3 of a cell inside the metal,
        # 2/3 outside) — the standard treatment of the CPW edge singularity.
        f"mesh.y = SmoothMeshLines([{width/2 - third:.9g} {width/2 + 2*third:.9g} {width/2 + gap - 2*third:.9g} {width/2 + gap + third:.9g}], {edge_res:.9g}, 1.3, 0);",
        f"mesh.y = SmoothMeshLines([0 mesh.y], {edge_res:.9g}, 1.3, 0);",
        "mesh.y = unique(sort([-mesh.y mesh.y]));",
        f"mesh.y = SmoothMeshLines([{-substrate_width/2 - air:.9g} {-substrate_width/2:.9g} mesh.y {substrate_width/2:.9g} {substrate_width/2 + air:.9g}], {air_res:.9g}, 1.4, 0);",
        # Resolve z at edge resolution within a few gap-widths of the metal
        # plane (the field-carrying region for a micron-scale cross-section),
        # a handful of lines through the substrate, wavelength-scale air.
        f"mesh.z = SmoothMeshLines([{substrate_h - 3*gap:.9g} {substrate_h:.9g} {substrate_h + 3*gap:.9g}], {edge_res:.9g}, 1.3, 0);",
        f"mesh.z = SmoothMeshLines([0 {substrate_h/2:.9g} mesh.z], {substrate_h/4:.9g}, 1.4, 0);",
        f"mesh.z = SmoothMeshLines([{-air:.9g} mesh.z {substrate_h + air:.9g}], {air_res:.9g}, 1.4, 0);",
        "CSX = DefineRectGrid(CSX, unit, mesh);",
        # SetMaterialProperty, not AddMaterial varargin: only the former sets
        # the real Epsilon (the latter silently produced a vacuum substrate).
        "CSX = AddMaterial(CSX, 'substrate');",
        f"CSX = SetMaterialProperty(CSX, 'substrate', 'Epsilon', {technology.substrate_epsilon_r:.12g});",
        f"CSX = AddBox(CSX, 'substrate', 0, [-{half:.9g} {-substrate_width/2:.9g} 0], [{half:.9g} {substrate_width/2:.9g} {substrate_h:.9g}]);",
        "CSX = AddMetal(CSX, 'CPW_PORT');",
        f"[CSX, port{{1}}] = AddCPWPort(CSX, 999, 1, 'CPW_PORT', [-{half:.9g} {-width/2:.9g} {substrate_h:.9g}], [-{half-port_length:.9g} {width/2:.9g} {substrate_h:.9g}], {gap:.9g}, 'x', [0 1 0], 'ExcitePort', true, 'MeasPlaneShift', {port_length:.9g}, 'Feed_R', 50);",
        f"[CSX, port{{2}}] = AddCPWPort(CSX, 999, 2, 'CPW_PORT', [{half:.9g} {-width/2:.9g} {substrate_h:.9g}], [{half-port_length:.9g} {width/2:.9g} {substrate_h:.9g}], {gap:.9g}, 'x', [0 1 0], 'MeasPlaneShift', {port_length:.9g}, 'Feed_R', 50);",
        "CSX = AddMetal(CSX, 'CPW');",
        f"CSX = AddBox(CSX, 'CPW', 999, [-{half-port_length:.9g} {-width/2:.9g} {substrate_h:.9g}], [{half-port_length:.9g} {width/2:.9g} {substrate_h:.9g}]);",
        "CSX = AddMetal(CSX, 'GND');",
        f"CSX = AddBox(CSX, 'GND', 999, [-{half:.9g} {-substrate_width/2:.9g} {substrate_h:.9g}], [{half:.9g} {-width/2-gap:.9g} {substrate_h:.9g}]);",
        f"CSX = AddBox(CSX, 'GND', 999, [-{half:.9g} {width/2+gap:.9g} {substrate_h:.9g}], [{half:.9g} {substrate_width/2:.9g} {substrate_h:.9g}]);",
        "Sim_Path = 'openems_run'; Sim_CSX = 'model.xml';",
        "CleanupSimPath(Sim_Path);",
        "WriteOpenEMS(fullfile(Sim_Path, Sim_CSX), FDTD, CSX);",
        "RunOpenEMS(Sim_Path, Sim_CSX);",
        "freq = linspace(f_start, f_stop, 401);",
        "port = calcPort(port, Sim_Path, freq, 'RefImpedance', 50);",
        "s11 = port{1}.uf.ref ./ port{1}.uf.inc;",
        "s21 = port{2}.uf.ref ./ port{1}.uf.inc;",
        "fid = fopen('openems_result.s2p', 'w'); fprintf(fid, '# Hz S RI R 50\\n');",
        "for k=1:numel(freq)",
        "  fprintf(fid, '%.12e %.12e %.12e %.12e %.12e %.12e %.12e %.12e %.12e\\n', freq(k), real(s11(k)), imag(s11(k)), real(s21(k)), imag(s21(k)), real(s21(k)), imag(s21(k)), real(s11(k)), imag(s11(k)));",
        "end; fclose(fid);",
        "fid = fopen('openems_metrics.csv', 'w');",
        "fprintf(fid, 'frequency_hz,z0_real,z0_imag,s11_real,s11_imag,s21_real,s21_imag\\n');",
        "for k=1:numel(freq)",
        "  fprintf(fid, '%.12e,%.12e,%.12e,%.12e,%.12e,%.12e,%.12e\\n', freq(k), real(port{1}.ZL(k)), imag(port{1}.ZL(k)), real(s11(k)), imag(s11(k)), real(s21(k)), imag(s21(k)));",
        "end; fclose(fid);",
    ]
    return "\n".join(lines) + "\n"


def prepare_spiral_fasthenry(
    spec: LayoutSpec, geometry: Geometry, technology: Technology, output_dir: str | Path
) -> SimulationResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    points = geometry.metadata.get("centerline_points_um")
    if not isinstance(points, list) or len(points) < 2:
        return SimulationResult(
            status="failed",
            solver="FastHenry",
            readiness_level=1,
            reason="Continuous centerline metadata is missing.",
            output_dir=out,
        )
    width = float(geometry.metadata["trace_width_um"])
    thickness = float(geometry.metadata["thickness_um"])
    lines = [
        "* Text-to-Layout square spiral",
        ".units um",
        ".default sigma=5.8e4",
    ]
    for index, point in enumerate(points, 1):
        x, y = point
        lines.append(f"N{index} x={x:.9g} y={y:.9g} z=0")
    for index in range(1, len(points)):
        lines.append(f"E{index} N{index} N{index + 1} w={width:.9g} h={thickness:.9g}")
    lines.extend((f".external N1 N{len(points)}", ".freq fmin=1e6 fmax=1e10 ndec=20", ".end"))
    input_path = out / "spiral.inp"
    input_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    warnings = (
        "A prepared deck alone is not evidence; retained Zc.mat and logs are required.",
        "Conductor conductivity and thickness are generic and require process replacement.",
    )
    manifest = _write_manifest(
        out, "FastHenry", spec.component, ("inductance", "resistance", "Q"), warnings
    )
    return SimulationResult(
        status="input_files_prepared",
        solver="FastHenry",
        readiness_level=2,
        reason="A continuous centerline and conductor cross-section were written as FastHenry input.",
        output_dir=out,
        artifacts={"input": str(input_path), "manifest": str(manifest)},
        warnings=warnings,
    )


def prepare_squid_plan(
    spec: LayoutSpec, geometry: Geometry, output_dir: str | Path
) -> SimulationResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    warnings = (
        "The two JJ polygons are generic process placeholders.",
        "No loop-inductance or Josephson simulation is valid until a foundry stack, Ic, and thickness are supplied.",
    )
    manifest = _write_manifest(
        out, "planned:FastHenry+Josephson-circuit-solver", spec.component, (), warnings, level=1
    )
    return SimulationResult(
        status="planned",
        solver="FastHenry + Josephson circuit solver",
        readiness_level=1,
        reason="Geometry exists, but process-specific junction and conductor parameters are absent.",
        output_dir=out,
        artifacts={"manifest": str(manifest)},
        warnings=warnings,
    )


def _write_manifest(
    out: Path,
    solver: str,
    component: str,
    expected: tuple[str, ...],
    warnings: tuple[str, ...],
    *,
    level: int = 2,
) -> Path:
    target = out / "simulation_manifest.json"
    data: dict[str, Any] = {
        "status": "input_files_prepared" if level >= 2 else "planned",
        "solver": solver,
        "component": component,
        "readiness_level": level,
        "expected_outputs": list(expected),
        "warnings": list(warnings),
        "solver_executed": False,
    }
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return target
