"""PSCAN2 input generation and guarded execution for IDC-derived LC/JJ checks.

PSCAN2 (http://pscan2sim.org/) is *not* a SPICE dialect: circuits are written
in its own netlist/HDL split with normalised (dimensionless) parameters and
are driven from Python. The templates here are therefore generated fresh in
the PSCAN2 style — JoSIM/WRspice decks are never reused — following the
structure documented in ``docs/references/jtwpa_numerical_simulations_review.md``
(netlist + ``.hdl`` parameter block + rc unit table + Python runner).

Detection order: explicit path → ``TEXTLAYOUT_PSCAN2`` → ``import pscan2``.
When PSCAN2 is absent the inputs are still generated and the result honestly
reports ``SKIPPED_PSCAN2_ABSENT``. The generated runner is defensive: it
verifies the import, reports the version, and exits with a distinct code when
programmatic execution is not wired, so an "executed" claim can never come
from a runner that did not actually simulate.
"""

from __future__ import annotations

import json
import math
import os
import shutil
import subprocess
import sys
from importlib.util import find_spec
from pathlib import Path
from typing import Any

from textlayout.simulation.base import CircuitSimulatorAdapter
from textlayout.simulation.models import SimulationResult, target_comparison
from textlayout.simulation.postprocess import estimate_resonance_ghz, parse_waveform_table
from textlayout.simulation.templates import LCResonanceCheck
from textlayout.solvers.base import run_subprocess

_ENV_VAR = "TEXTLAYOUT_PSCAN2"

PSCAN2_INPUT_PREPARED = "PSCAN2_INPUT_PREPARED"
SKIPPED_PSCAN2_ABSENT = "SKIPPED_SOLVER_ABSENT"
PSCAN2_EXECUTED = "PSCAN2_EXECUTED"
PSCAN2_TRANSIENT_PARSED = "PSCAN2_TRANSIENT_PARSED"
PSCAN2_RESONANCE_CHECKED = "PSCAN2_RESONANCE_CHECKED"
PSCAN2_GAIN_CHECKED = "PSCAN2_GAIN_CHECKED"

#: Runner exit codes — the contract between generated script and this module.
_RC_WAVEFORM_WRITTEN = 0
_RC_EXECUTION_NOT_WIRED = 3
_RC_PSCAN2_ABSENT = 4

# Normalisation chosen for the generated files (PSCAN2 works in dimensionless
# units with the flux quantum set to 2*pi). With t0 = 1 ps and L0 = 1 pH the
# derived units are C0 = t0^2/L0 = 1 pF and R0 = L0/t0 = 1 Ohm.
_UNIT_TABLE = {
    "time_ps": 1.0,
    "inductance_ph": 1.0,
    "capacitance_pf": 1.0,
    "resistance_ohm": 1.0,
}


def find_pscan2(explicit: str | None = None) -> list[str] | None:
    """Return the command prefix that can execute the generated runner.

    - explicit/env value pointing at an executable → ``[that, runner]``
    - otherwise, if the ``pscan2`` Python module is importable in this
      interpreter → ``[sys.executable, runner]``
    - otherwise ``None`` (absent).
    """
    candidate = explicit or os.environ.get(_ENV_VAR)
    if candidate:
        path = Path(candidate)
        if path.is_file():
            return [str(path)]
        resolved = shutil.which(candidate)
        return [resolved] if resolved else None
    try:
        if find_spec("pscan2") is not None:
            return [sys.executable]
    except (ImportError, ValueError):
        return None
    return None


def pscan2_version() -> str | None:
    """Version of the importable pscan2 module, if any (no subprocess)."""
    try:
        if find_spec("pscan2") is None:
            return None
        import pscan2  # type: ignore[import-not-found]  # noqa: PLC0415

        version = getattr(pscan2, "__version__", None)
        return str(version) if version is not None else "pscan2 (version attribute absent)"
    except Exception:  # noqa: BLE001 — optional third-party import must never crash us
        return None


def prepare_idc_pscan2(
    output_dir: str | Path,
    *,
    capacitance_pf: float,
    capacitance_source: str,
    stray_inductance_nh: float | None = None,
    target_frequency_ghz: float | None = None,
    include_jj: bool = False,
) -> SimulationResult:
    """Generate PSCAN2-style netlist, parameter, rc, and runner files.

    Only files are written; nothing executes. The passive LC check mirrors the
    JoSIM/WRspice templates in physics but not in syntax.
    """
    if capacitance_pf <= 0:
        raise ValueError("capacitance_pf must be positive")
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    if stray_inductance_nh is None:
        frequency = (target_frequency_ghz or 6.0) * 1e9
        stray_inductance_nh = (
            1.0 / ((2.0 * math.pi * frequency) ** 2 * capacitance_pf * 1e-12) * 1e9
        )
    expected_ghz = (
        1.0 / (2.0 * math.pi * math.sqrt(stray_inductance_nh * 1e-9 * capacitance_pf * 1e-12)) / 1e9
    )
    # Normalised values under the declared unit table (L0=1pH, C0=1pF, t0=1ps).
    c_norm = capacitance_pf / _UNIT_TABLE["capacitance_pf"]
    l_norm = stray_inductance_nh * 1e3 / _UNIT_TABLE["inductance_ph"]

    netlist = out / "lc_check.cir"
    netlist.write_text(
        "\n".join(
            (
                "# Passive LC resonance check generated by textlayout (PSCAN2 dialect)",
                "# Values are normalised; see lc_check.hdl and pscan_units.py",
                "# I1 drives the resonator; R1 terminates the source",
                "I1 0 N001 I",
                "R1 0 N001 R",
                "L1 N001 0 L",
                "C1 N001 0 C",
                ".end",
            )
        )
        + "\n",
        encoding="ascii",
    )
    hdl = out / "lc_check.hdl"
    hdl.write_text(
        "\n".join(
            (
                "# Normalised circuit parameters (unit table in pscan_units.py)",
                "PARAMETER",
                f"    L = {l_norm:.9g},",
                f"    C = {c_norm:.9g},",
                "    R = 50.0,",
                "    pi = 3.141592653589793;",
                "CIRCUIT lc_check()",
                "{",
                "INTERNAL",
                "    # Pulse-like drive: short raised-cosine kick, then ringdown",
                "    i = (tcurr < 6.283) ? 0.5*(1.0 - cos(tcurr)) : 0.0;",
                "}",
            )
        )
        + "\n",
        encoding="ascii",
    )
    units = out / "pscan_units.py"
    units.write_text(
        "\n".join(
            (
                '"""Unit normalisation for the textlayout-generated PSCAN2 inputs."""',
                "# Base units: t0 = 1 ps, L0 = 1 pH  =>  C0 = 1 pF, R0 = 1 Ohm.",
                "# The magnetic flux quantum is 2*pi in PSCAN2's internal units.",
                f"DIM_UNITS = {json.dumps(_UNIT_TABLE)}",
                "",
            )
        ),
        encoding="ascii",
    )
    waveform = out / "waveform.csv"
    runner = out / "runner.py"
    runner.write_text(_runner_source(waveform.name), encoding="ascii")

    artifacts = {
        "input": str(netlist),
        "hdl": str(hdl),
        "units": str(units),
        "runner": str(runner),
        "expected_output": str(waveform),
    }
    if include_jj:
        jj = out / "jj_check.cir"
        jj.write_text(
            "\n".join(
                (
                    "# JJ-ready transient check generated by textlayout (PSCAN2 dialect)",
                    "# rsj(IC, RN, CJ) junction parameters are normalised placeholders;",
                    "# supply process values before drawing conclusions.",
                    "I1 0 N001 I",
                    "R1 0 N001 R",
                    "J1 N001 0 rsj(IC1, RN1, CJ1)",
                    "L1 N001 0 L",
                    "C1 N001 0 C",
                    ".end",
                )
            )
            + "\n",
            encoding="ascii",
        )
        artifacts["jj_input"] = str(jj)
    manifest = out / "manifest.json"
    manifest.write_text(
        json.dumps(
            {
                "schema": "textlayout.pscan2-input.v1",
                "evidence_level": PSCAN2_INPUT_PREPARED,
                "capacitance_pf": capacitance_pf,
                "capacitance_source": capacitance_source,
                "stray_inductance_nh": stray_inductance_nh,
                "analytical_resonance_ghz": expected_ghz,
                "unit_table": _UNIT_TABLE,
                "solver_executed": False,
                "parametric_gain_claimed": False,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    artifacts["manifest"] = str(manifest)
    return SimulationResult(
        status="input_files_prepared",
        solver="PSCAN2",
        readiness_level=2,
        reason="PSCAN2-style LC input, unit table, and Python runner were generated; "
        "PSCAN2 was not run.",
        output_dir=out,
        artifacts=artifacts,
        extracted_quantities={"analytical_resonance_ghz": expected_ghz},
        warnings=(
            f"IDC capacitance source is {capacitance_source}; PSCAN2 is a circuit "
            "simulator and never validates the physical geometry's capacitance.",
            "PSCAN2 uses normalised units; verify the unit table before manual runs.",
        ),
        evidence_level=PSCAN2_INPUT_PREPARED,
    )


def _runner_source(waveform_name: str) -> str:
    """Source of the generated, defensive PSCAN2 runner script."""
    return (
        '"""PSCAN2 runner generated by textlayout.\n'
        "\n"
        "Exit codes (contract with textlayout.simulation.pscan2):\n"
        f"  {_RC_WAVEFORM_WRITTEN} - transient ran and {waveform_name} was written\n"
        f"  {_RC_EXECUTION_NOT_WIRED} - pscan2 importable, but programmatic execution "
        "is not wired yet\n"
        f"  {_RC_PSCAN2_ABSENT} - the pscan2 module is not importable\n"
        '"""\n'
        "import importlib.util\n"
        "import sys\n"
        "\n"
        'if importlib.util.find_spec("pscan2") is None:\n'
        '    print("pscan2 module not importable in", sys.executable)\n'
        f"    sys.exit({_RC_PSCAN2_ABSENT})\n"
        "\n"
        "import pscan2  # noqa: E402\n"
        "\n"
        'print("pscan2 version:", getattr(pscan2, "__version__", "unknown"))\n'
        "# textlayout deliberately does not guess at the PSCAN2 driver API.\n"
        "# To wire a real run: load lc_check.cir/.hdl with the pscan2 API,\n"
        f'# run the transient, and write time/value columns to "{waveform_name}"\n'
        "# (CSV, first column time in seconds), then exit 0.\n"
        f"sys.exit({_RC_EXECUTION_NOT_WIRED})\n"
    )


def run_idc_pscan2(
    prepared: SimulationResult,
    *,
    executable: str | None = None,
    timeout_seconds: int = 600,
    resonance_tolerance_percent: float = 10.0,
) -> SimulationResult:
    """Execute the generated runner if PSCAN2 is reachable; stay honest if not."""
    runner = Path(prepared.artifacts.get("runner", ""))
    if not runner.is_file():
        return _terminal(prepared, "failed", "No PSCAN2 runner was prepared.", None)
    command_prefix = find_pscan2(executable)
    if command_prefix is None:
        return SimulationResult(
            status="skipped",
            solver="PSCAN2",
            readiness_level=2,
            reason="PSCAN2 is not installed (no TEXTLAYOUT_PSCAN2 and the pscan2 "
            "module is not importable); inputs remain prepared.",
            output_dir=prepared.output_dir,
            artifacts=prepared.artifacts,
            extracted_quantities=prepared.extracted_quantities,
            warnings=prepared.warnings,
            evidence_level=SKIPPED_PSCAN2_ABSENT,
        )
    output = Path(prepared.artifacts["expected_output"])
    if output.exists():
        output.unlink()
    try:
        execution = run_subprocess(
            [*command_prefix, runner.name],
            cwd=runner.parent,
            timeout_seconds=timeout_seconds,
            log_prefix="pscan2",
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return _terminal(prepared, "failed", f"PSCAN2 runner execution failed: {exc}", None)
    artifacts = {
        **prepared.artifacts,
        "solver_stdout": str(execution.stdout_path),
        "solver_stderr": str(execution.stderr_path),
    }
    base: dict[str, Any] = dict(
        solver="PSCAN2",
        output_dir=prepared.output_dir,
        artifacts=artifacts,
        warnings=prepared.warnings,
        command=execution.command,
        return_code=execution.returncode,
        runtime_seconds=execution.runtime_seconds,
        solver_version=pscan2_version(),
    )
    if execution.returncode == _RC_PSCAN2_ABSENT:
        return SimulationResult(
            status="skipped",
            readiness_level=2,
            reason="The runner interpreter cannot import pscan2; inputs remain prepared.",
            extracted_quantities=prepared.extracted_quantities,
            evidence_level=SKIPPED_PSCAN2_ABSENT,
            **base,
        )
    if execution.returncode == _RC_EXECUTION_NOT_WIRED:
        return SimulationResult(
            status="input_files_prepared",
            readiness_level=2,
            reason="pscan2 is importable but programmatic execution is not wired; "
            "no simulation was run and no execution is claimed.",
            extracted_quantities=prepared.extracted_quantities,
            evidence_level=PSCAN2_INPUT_PREPARED,
            **base,
        )
    if (
        execution.returncode != _RC_WAVEFORM_WRITTEN
        or not output.is_file()
        or output.stat().st_size == 0
    ):
        return SimulationResult(
            status="failed",
            readiness_level=2,
            reason=f"PSCAN2 runner exited {execution.returncode} without a waveform.",
            evidence_level="FAILED",
            **base,
        )
    artifacts["result"] = str(output)
    try:
        transient = parse_waveform_table(output)
    except ValueError as exc:
        return SimulationResult(
            status="executed",
            readiness_level=3,
            reason=f"PSCAN2 ran but the waveform could not be parsed: {exc}",
            evidence_level=PSCAN2_EXECUTED,
            **base,
        )
    extracted: dict[str, Any] = {
        "sample_count": len(transient["time_s"]),
        "signal_names": list(transient["signals"]),
    }
    level = PSCAN2_TRANSIENT_PARSED
    reason = "PSCAN2 transient output was parsed."
    expected = prepared.extracted_quantities.get("analytical_resonance_ghz")
    voltage = next(iter(transient["signals"].values()), [])
    measured = estimate_resonance_ghz(transient["time_s"], voltage)
    comparison = None
    if measured is not None and isinstance(expected, (int, float)):
        extracted["resonance_ghz"] = measured
        comparison = target_comparison(
            measured, float(expected), resonance_tolerance_percent, "resonance_ghz"
        )
        level = PSCAN2_RESONANCE_CHECKED
        reason = "PSCAN2 transient resonance was extracted and compared with analytical LC."
    return SimulationResult(
        status="executed",
        readiness_level=4 if comparison else 3,
        reason=reason,
        extracted_quantities=extracted,
        target_comparison=comparison,
        evidence_level=level,
        **base,
    )


def _terminal(
    prepared: SimulationResult, status: str, reason: str, level: str | None
) -> SimulationResult:
    return SimulationResult(
        status=status,
        solver="PSCAN2",
        readiness_level=prepared.readiness_level,
        reason=reason,
        output_dir=prepared.output_dir,
        artifacts=prepared.artifacts,
        warnings=prepared.warnings,
        evidence_level=level,
    )


class PSCAN2Adapter(CircuitSimulatorAdapter):
    """PSCAN2 behind the shared circuit-simulator lifecycle."""

    name = "PSCAN2"
    env_var = _ENV_VAR
    executable_names = ("pscan2",)

    def discover(self, explicit: str | None = None) -> str | None:
        prefix = find_pscan2(explicit)
        return prefix[0] if prefix else None

    def version(self, explicit: str | None = None) -> str | None:
        return pscan2_version()

    def prepare(self, template: LCResonanceCheck, output_dir: str | Path) -> SimulationResult:
        return prepare_idc_pscan2(
            output_dir,
            capacitance_pf=template.capacitance_pf,
            capacitance_source=template.capacitance_source,
            stray_inductance_nh=template.inductance_nh,
        )

    def run(
        self,
        prepared: SimulationResult,
        *,
        executable: str | None = None,
        timeout_seconds: int = 600,
    ) -> SimulationResult:
        return run_idc_pscan2(prepared, executable=executable, timeout_seconds=timeout_seconds)
