"""JoSIM netlist generation, execution, and CSV parsing for SQUID candidates."""

from __future__ import annotations

import csv
import json
import shutil
import subprocess
from pathlib import Path

from textlayout.models import Geometry, Technology
from textlayout.research.formulas import rectangular_loop_inductance_ph
from textlayout.schemas.dsl import LayoutSpec
from textlayout.simulation.models import SimulationResult, target_comparison
from textlayout.solvers.base import run_subprocess

_NAMES = ("josim-cli", "josim-cli.exe", "josim", "josim.exe")


def prepare_squid_josim(
    spec: LayoutSpec,
    geometry: Geometry,
    technology: Technology,
    output_dir: str | Path,
) -> SimulationResult:
    """Write a two-junction RCSJ SQUID deck when process inputs are explicit."""
    del technology
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    required = (
        "critical_current_ua",
        "shunt_resistance_ohm",
        "junction_capacitance_ff",
    )
    missing = [name for name in required if spec.parameters.get(name) is None]
    if missing:
        return _squid_plan(spec, out, missing)

    ic_ua = float(spec.parameters["critical_current_ua"])
    resistance = float(spec.parameters["shunt_resistance_ohm"])
    capacitance_ff = float(spec.parameters["junction_capacitance_ff"])
    loop_l_ph = spec.parameters.get("loop_inductance_ph")
    if loop_l_ph is None:
        loop_l_ph = rectangular_loop_inductance_ph(
            float(spec.parameters["loop_inner_width_um"]),
            float(spec.parameters["loop_inner_height_um"]),
            float(spec.parameters["trace_width_um"]),
        )
    max_bias_ua = max(4.0 * ic_ua, 1.0)
    netlist = out / "squid.cir"
    result_csv = out / "squid_result.csv"
    iv_csv = out / "junction_iv.csv"
    netlist.write_text(
        "\n".join(
            (
                "* Two-junction DC SQUID candidate generated by textlayout",
                f".model SQUIDJJ jj(ic={ic_ua * 1e-6:.12g} rn={resistance:.12g} "
                f"r0={resistance:.12g} c={capacitance_ff * 1e-15:.12g})",
                f"IBIAS TOP 0 pwl(0 0 1n 0 20n {max_bias_ua * 1e-6:.12g})",
                "BJ1 TOP LEFT SQUIDJJ",
                "BJ2 TOP RIGHT SQUIDJJ",
                f"LLEFT LEFT 0 {float(loop_l_ph) * 0.5e-12:.12g}",
                f"LRIGHT RIGHT 0 {float(loop_l_ph) * 0.5e-12:.12g}",
                ".tran 1p 20n 5n 10p",
                ".print v(TOP) i(IBIAS) p(BJ1) p(BJ2)",
                f".iv SQUIDJJ {max_bias_ua * 1e-6:.12g} {iv_csv.name}",
                ".end",
            )
        ) + "\n",
        encoding="ascii",
    )
    manifest = out / "simulation_manifest.json"
    manifest.write_text(
        json.dumps(
            {
                "schema": "textlayout.simulation-input.v1",
                "status": "input_files_prepared",
                "solver": "JoSIM",
                "component": "SQUID",
                "output": result_csv.name,
                "critical_current_ua": ic_ua,
                "loop_inductance_ph": loop_l_ph,
                "geometry_loop_area_um2": geometry.metadata.get("loop_area_um2"),
                "limitations": [
                    "Circuit-level RCSJ verification only; junction geometry-to-Ic is an explicit input.",
                    "The loop inductance is analytical unless a separately extracted value is supplied.",
                ],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return SimulationResult(
        status="input_files_prepared",
        solver="JoSIM",
        readiness_level=2,
        reason="JoSIM RCSJ SQUID netlist generated from explicit junction parameters.",
        output_dir=out,
        artifacts={"input": str(netlist), "manifest": str(manifest), "expected_output": str(result_csv)},
        warnings=(
            "JoSIM verifies circuit behavior, not fabrication validity of the JJ polygons.",
        ),
    )


def _squid_plan(spec: LayoutSpec, out: Path, missing: list[str]) -> SimulationResult:
    manifest = out / "simulation_manifest.json"
    manifest.write_text(
        json.dumps(
            {
                "status": "planned",
                "solver": "JoSIM",
                "component": spec.component,
                "solver_executed": False,
                "missing_explicit_parameters": missing,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return SimulationResult(
        status="planned",
        solver="JoSIM",
        readiness_level=1,
        reason="JoSIM input was not generated because process parameters are missing: "
        + ", ".join(missing),
        output_dir=out,
        artifacts={"manifest": str(manifest)},
        warnings=("No junction parameter was inferred from generic placeholder geometry.",),
    )


def run_josim(
    prepared: SimulationResult,
    *,
    executable: str | None = None,
    timeout_seconds: int = 600,
    target_voltage_uv: float | None = None,
    tolerance_pct: float = 20.0,
) -> SimulationResult:
    input_path = Path(prepared.artifacts.get("input", ""))
    if not input_path.is_file():
        return SimulationResult(
            status="failed",
            solver=prepared.solver,
            readiness_level=prepared.readiness_level,
            reason="No JoSIM circuit input was prepared.",
            output_dir=prepared.output_dir,
            artifacts=prepared.artifacts,
            warnings=prepared.warnings,
        )
    solver = _find(executable)
    if solver is None:
        return SimulationResult(
            status="skipped",
            solver=prepared.solver,
            readiness_level=prepared.readiness_level,
            reason="JoSIM executable not found; install josim-cli or pass --executable.",
            output_dir=prepared.output_dir,
            artifacts=prepared.artifacts,
            warnings=prepared.warnings,
        )
    output = input_path.parent / "squid_result.csv"
    try:
        execution = run_subprocess(
            [solver, "-o", output.name, input_path.name],
            cwd=input_path.parent,
            timeout_seconds=timeout_seconds,
            log_prefix="solver",
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return _failed(prepared, f"JoSIM execution failed: {exc}")
    artifacts = {
        **prepared.artifacts,
        "solver_stdout": str(execution.stdout_path),
        "solver_stderr": str(execution.stderr_path),
    }
    if execution.returncode != 0 or not output.is_file() or output.stat().st_size == 0:
        return _failed(prepared, f"JoSIM exited {execution.returncode} without CSV output.", artifacts)
    try:
        values = parse_josim_csv(output)
    except ValueError as exc:
        return _failed(prepared, f"JoSIM CSV could not be parsed: {exc}", artifacts)
    comparison = target_comparison(
        values["mean_voltage_uv"], target_voltage_uv, tolerance_pct, "mean_voltage_uv"
    )
    return SimulationResult(
        status="executed",
        solver=Path(solver).name,
        readiness_level=4 if comparison else 3,
        reason="JoSIM produced a parseable RCSJ transient CSV.",
        output_dir=prepared.output_dir,
        artifacts={**artifacts, "result": str(output)},
        extracted_quantities=values,
        target_comparison=comparison,
        warnings=prepared.warnings,
        command=execution.command,
    )


def parse_josim_csv(path: str | Path) -> dict[str, float]:
    """Extract steady-state mean and modulation span from JoSIM CSV output."""
    with Path(path).open(newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        raise ValueError("no data rows")
    voltage_key = next(
        (key for key in rows[0] if key and ("V(TOP" in key.upper() or "NODEV" in key.upper())),
        None,
    )
    if voltage_key is None:
        raise ValueError("no TOP-node voltage column")
    try:
        voltages = [float(row[voltage_key]) for row in rows[len(rows) // 2 :]]
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError("non-numeric voltage samples") from exc
    return {
        "mean_voltage_uv": sum(voltages) / len(voltages) * 1e6,
        "voltage_span_uv": (max(voltages) - min(voltages)) * 1e6,
    }


def _find(explicit: str | None) -> str | None:
    if explicit:
        path = Path(explicit)
        return str(path) if path.is_file() else shutil.which(explicit)
    return next((found for name in _NAMES if (found := shutil.which(name))), None)


def _failed(
    prepared: SimulationResult, reason: str, artifacts: dict[str, str] | None = None
) -> SimulationResult:
    return SimulationResult(
        status="failed",
        solver=prepared.solver,
        readiness_level=prepared.readiness_level,
        reason=reason,
        output_dir=prepared.output_dir,
        artifacts=artifacts or prepared.artifacts,
        warnings=prepared.warnings,
    )
