"""Honest input preparation for openEMS and FastHenry benchmarks."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from textlayout.models import Geometry, Technology
from textlayout.schemas.dsl import LayoutSpec
from textlayout.simulation.models import SimulationResult


def prepare_cpw_openems(
    spec: LayoutSpec, geometry: Geometry, technology: Technology, output_dir: str | Path
) -> SimulationResult:
    return _prepare_openems(
        spec,
        geometry,
        technology,
        output_dir,
        expected=("Z0", "S11", "S21", "effective_permittivity"),
    )


def prepare_resonator_openems(
    spec: LayoutSpec, geometry: Geometry, technology: Technology, output_dir: str | Path
) -> SimulationResult:
    return _prepare_openems(
        spec,
        geometry,
        technology,
        output_dir,
        expected=("resonance_frequency", "loaded_Q", "S21"),
    )


def _prepare_openems(
    spec: LayoutSpec,
    geometry: Geometry,
    technology: Technology,
    output_dir: str | Path,
    *,
    expected: tuple[str, ...],
) -> SimulationResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    config = out / "openems_model.json"
    driver = out / "openems_model.m"
    bbox = geometry.bbox()
    payload = {
        "status": "input_files_prepared",
        "solver": "openEMS",
        "component": spec.component,
        "target": dict(spec.target),
        "technology": technology.name,
        "substrate_epsilon_r": technology.substrate_epsilon_r,
        "bbox_um": [bbox.xmin, bbox.ymin, bbox.xmax, bbox.ymax],
        "ports": [
            {
                "name": port.name,
                "center_um": list(port.center),
                "width_um": port.width,
                "orientation_deg": port.orientation,
                "layer": port.layer,
            }
            for port in geometry.ports
        ],
        "expected_outputs": list(expected),
        "execution": "not_run",
        "driver": driver.name,
    }
    config.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    driver.write_text(_render_openems_octave(spec, geometry, technology), encoding="utf-8")
    warnings = (
        "The Octave driver is runnable only with the external openEMS/CSXCAD stack installed.",
        "Boundary placement and mesh convergence must be reviewed before signoff.",
    )
    manifest = _write_manifest(out, "openEMS", spec.component, expected, warnings)
    return SimulationResult(
        status="input_files_prepared",
        solver="openEMS",
        readiness_level=2,
        reason="A runnable openEMS/CSXCAD Octave model and manifest were generated.",
        output_dir=out,
        artifacts={"model": str(config), "driver": str(driver), "manifest": str(manifest)},
        warnings=warnings,
    )


def _render_openems_octave(spec: LayoutSpec, geometry: Geometry, technology: Technology) -> str:
    """Render a self-contained openEMS Octave driver from verified polygons.

    The port call deliberately uses openEMS' native ``AddCPWPort`` API for a
    straight CPW.  Resonators use calibrated lumped ports on the feedline,
    because a hanger is not itself a through CPW-port cross-section.
    """
    bbox = geometry.bbox()
    margin = max(bbox.width, bbox.height) * 0.15 + 50.0
    f0 = float(spec.target.get("frequency_ghz", 6.0)) * 1e9
    f_start = max(1e6, f0 * 0.5)
    f_stop = f0 * 1.5
    substrate_h = 500.0
    lines = [
        "% Generated by textlayout; units are micrometres.",
        "close all; clear; clc;",
        "physical_constants;",
        "unit = 1e-6;",
        f"f_start = {f_start:.12g}; f_stop = {f_stop:.12g};",
        "FDTD = InitFDTD('EndCriteria', 1e-5);",
        "FDTD = SetGaussExcite(FDTD, (f_start+f_stop)/2, (f_stop-f_start)/2);",
        "FDTD = SetBoundaryCond(FDTD, {'PML_8','PML_8','PML_8','PML_8','PML_8','PML_8'});",
        "CSX = InitCSX();",
        f"CSX = AddMaterial(CSX, 'substrate', 'Epsilon', {technology.substrate_epsilon_r:.12g});",
        (
            "CSX = AddBox(CSX, 'substrate', 0, "
            f"[{bbox.xmin - margin:.9g} {bbox.ymin - margin:.9g} {-substrate_h:.9g}], "
            f"[{bbox.xmax + margin:.9g} {bbox.ymax + margin:.9g} 0]);"
        ),
        "CSX = AddMetal(CSX, 'metal');",
    ]
    for index, polygon in enumerate(geometry.polygons):
        if polygon.layer != str(spec.parameters.get("metal", "M1")):
            continue
        xs = " ".join(f"{point[0]:.9g}" for point in polygon.points)
        ys = " ".join(f"{point[1]:.9g}" for point in polygon.points)
        lines.extend(
            (
                f"p{index} = [{xs}; {ys}];",
                f"CSX = AddPolygon(CSX, 'metal', 10, 'z', 0, p{index});",
            )
        )
    lines.extend(
        (
            (
                "mesh.x = SmoothMeshLines(["
                f"{bbox.xmin - margin:.9g} {bbox.xmax + margin:.9g}], 20, 1.4);"
            ),
            (
                "mesh.y = SmoothMeshLines(["
                f"{bbox.ymin - margin:.9g} {bbox.ymax + margin:.9g}], 20, 1.4);"
            ),
            f"mesh.z = SmoothMeshLines([{-substrate_h:.9g} 0 100], 20, 1.4);",
            "CSX = DefineRectGrid(CSX, unit, mesh);",
        )
    )
    if spec.component == "CPW":
        width = float(spec.parameters["center_width_um"])
        gap = float(spec.parameters["gap_um"])
        length = float(spec.parameters["length_um"])
        x0 = (bbox.xmin + bbox.xmax) / 2.0
        lines.extend(
            (
                (
                    "[CSX, port{1}] = AddCPWPort(CSX, 999, 1, 'metal', "
                    f"[{x0 - width / 2:.9g} {bbox.ymin:.9g} {-substrate_h:.9g}], "
                    f"[{x0 + width / 2:.9g} {bbox.ymin + min(length * 0.1, 100):.9g} 50], "
                    f"{gap:.9g}, 'y', [1 0 0], 'ExcitePort', true);"
                ),
                (
                    "[CSX, port{2}] = AddCPWPort(CSX, 999, 2, 'metal', "
                    f"[{x0 - width / 2:.9g} {bbox.ymax - min(length * 0.1, 100):.9g} {-substrate_h:.9g}], "
                    f"[{x0 + width / 2:.9g} {bbox.ymax:.9g} 50], "
                    f"{gap:.9g}, 'y', [1 0 0]);"
                ),
            )
        )
    else:
        # Feedline ports for the hanger; the first is excited.
        for number, port in enumerate(geometry.ports[:2], 1):
            x, y = port.center
            excite = 1 if number == 1 else 0
            lines.append(
                f"[CSX, port{{{number}}}] = AddLumpedPort(CSX, {number}, 50, "
                f"[{x - 5:.9g} {y - 5:.9g} -1], [{x + 5:.9g} {y + 5:.9g} 1], "
                f"'x', {excite});"
            )
    lines.extend(
        (
            "Sim_Path = 'openems_run'; Sim_CSX = 'model.xml';",
            "[status, message] = rmdir(Sim_Path, 's'); mkdir(Sim_Path);",
            "WriteOpenEMS(fullfile(Sim_Path, Sim_CSX), FDTD, CSX);",
            "RunOpenEMS(Sim_Path, Sim_CSX);",
            "freq = linspace(f_start, f_stop, 401);",
            "port = calcPort(port, Sim_Path, freq);",
            "s11 = port{1}.uf.ref ./ port{1}.uf.inc;",
            "s21 = port{2}.uf.ref ./ port{1}.uf.inc;",
            "fid = fopen('openems_result.s2p', 'w');",
            "fprintf(fid, '# Hz S RI R 50\\n');",
            "for k=1:numel(freq)",
            "  fprintf(fid, '%.12e %.12e %.12e %.12e %.12e %.12e %.12e %.12e %.12e\\n', freq(k), real(s11(k)), imag(s11(k)), real(s21(k)), imag(s21(k)), real(s21(k)), imag(s21(k)), real(s11(k)), imag(s11(k)));",
            "end",
            "fclose(fid);",
        )
    )
    return "\n".join(lines) + "\n"


def prepare_spiral_fasthenry(
    spec: LayoutSpec, geometry: Geometry, technology: Technology, output_dir: str | Path
) -> SimulationResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    points = geometry.metadata.get("centerline_points_um")
    if not isinstance(points, list) or len(points) < 2:
        return SimulationResult(
            status="failed",
            solver="FastHenry",
            readiness_level=1,
            reason="Continuous centerline metadata is missing.",
            output_dir=out,
        )
    width = float(geometry.metadata["trace_width_um"])
    thickness = float(geometry.metadata["thickness_um"])
    lines = [
        "* Text-to-Layout square spiral",
        ".units um",
        ".default sigma=5.8e4",
    ]
    for index, point in enumerate(points, 1):
        x, y = point
        lines.append(f"N{index} x={x:.9g} y={y:.9g} z=0")
    for index in range(1, len(points)):
        lines.append(f"E{index} N{index} N{index + 1} w={width:.9g} h={thickness:.9g}")
    lines.extend((f".external N1 N{len(points)}", ".freq fmin=1e6 fmax=1e10 ndec=20", ".end"))
    input_path = out / "spiral.inp"
    input_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    warnings = (
        "FastHenry has not been executed; no inductance, resistance, or Q result is claimed.",
        "Conductor conductivity and thickness are generic and require process replacement.",
    )
    manifest = _write_manifest(
        out, "FastHenry", spec.component, ("inductance", "resistance", "Q"), warnings
    )
    return SimulationResult(
        status="input_files_prepared",
        solver="FastHenry",
        readiness_level=2,
        reason="A continuous centerline and conductor cross-section were written as FastHenry input.",
        output_dir=out,
        artifacts={"input": str(input_path), "manifest": str(manifest)},
        warnings=warnings,
    )


def prepare_squid_plan(
    spec: LayoutSpec, geometry: Geometry, output_dir: str | Path
) -> SimulationResult:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    warnings = (
        "The two JJ polygons are generic process placeholders.",
        "No loop-inductance or Josephson simulation is valid until a foundry stack, Ic, and thickness are supplied.",
    )
    manifest = _write_manifest(
        out, "planned:FastHenry+Josephson-circuit-solver", spec.component, (), warnings, level=1
    )
    return SimulationResult(
        status="planned",
        solver="FastHenry + Josephson circuit solver",
        readiness_level=1,
        reason="Geometry exists, but process-specific junction and conductor parameters are absent.",
        output_dir=out,
        artifacts={"manifest": str(manifest)},
        warnings=warnings,
    )


def _write_manifest(
    out: Path,
    solver: str,
    component: str,
    expected: tuple[str, ...],
    warnings: tuple[str, ...],
    *,
    level: int = 2,
) -> Path:
    target = out / "simulation_manifest.json"
    data: dict[str, Any] = {
        "status": "input_files_prepared" if level >= 2 else "planned",
        "solver": solver,
        "component": component,
        "readiness_level": level,
        "expected_outputs": list(expected),
        "warnings": list(warnings),
        "solver_executed": False,
    }
    target.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return target
