"""WRspice deck generation, guarded execution, and rawfile parsing.

WRspice (Whiteley Research, http://wrcad.com) is a SPICE-family simulator
with native Josephson-junction support. Its dialect is *not* JoSIM's:
analysis and output live in a ``.control`` block, waveforms are saved with
``write``, and the JJ element/model syntax is
``Bxxx n+ n- model`` with ``.model name jj(level=1) icrit=... cap=...`` —
both confirmed against the published SNAIL-TWPA deck reviewed in
``docs/references/jtwpa_numerical_simulations_review.md``. All numeric values
are emitted in plain exponent notation so no SPICE suffix ambiguity can bite.

Detection order: explicit path → ``TEXTLAYOUT_WRSPICE`` → ``wrspice`` /
``wrspice64`` on PATH. When absent, decks are still generated and the result
reports ``SKIPPED_WRSPICE_ABSENT``.
"""

from __future__ import annotations

import json
import math
import subprocess
from pathlib import Path
from typing import Any

from textlayout.simulation.base import CircuitSimulatorAdapter, capture_version, find_simulator
from textlayout.simulation.models import SimulationResult, target_comparison
from textlayout.simulation.postprocess import (
    Waveform,
    estimate_resonance_ghz,
    parse_waveform_table,
)
from textlayout.simulation.templates import LCResonanceCheck
from textlayout.solvers.base import run_subprocess

_ENV_VAR = "TEXTLAYOUT_WRSPICE"
_NAMES = ("wrspice", "wrspice64", "wrspice.exe", "wrspice64.exe")

WRSPICE_INPUT_PREPARED = "WRSPICE_INPUT_PREPARED"
SKIPPED_WRSPICE_ABSENT = "SKIPPED_SOLVER_ABSENT"
WRSPICE_EXECUTED = "WRSPICE_EXECUTED"
WRSPICE_TRANSIENT_PARSED = "WRSPICE_TRANSIENT_PARSED"
WRSPICE_RESONANCE_CHECKED = "WRSPICE_RESONANCE_CHECKED"
WRSPICE_GAIN_CHECKED = "WRSPICE_GAIN_CHECKED"


def find_wrspice(explicit: str | None = None) -> str | None:
    return find_simulator(_ENV_VAR, _NAMES, explicit, tool_subdir="wrspice")


def prepare_idc_wrspice(
    output_dir: str | Path,
    *,
    capacitance_pf: float,
    capacitance_source: str,
    stray_inductance_nh: float | None = None,
    target_frequency_ghz: float | None = None,
    include_jj: bool = False,
) -> SimulationResult:
    """Generate the passive-LC (and optional JJ-ready) WRspice decks."""
    if capacitance_pf <= 0:
        raise ValueError("capacitance_pf must be positive")
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    if stray_inductance_nh is None:
        frequency = (target_frequency_ghz or 6.0) * 1e9
        stray_inductance_nh = (
            1.0 / ((2.0 * math.pi * frequency) ** 2 * capacitance_pf * 1e-12) * 1e9
        )
    expected_ghz = (
        1.0 / (2.0 * math.pi * math.sqrt(stray_inductance_nh * 1e-9 * capacitance_pf * 1e-12)) / 1e9
    )
    circuit = out / "lc_check.cir"
    output = out / "lc_result.raw"
    circuit.write_text(
        "\n".join(
            (
                "* IDC passive LC transient check generated by textlayout (WRspice dialect)",
                "* Plain exponent notation throughout; no SPICE unit suffixes.",
                "VDRIVE IN 0 pulse(0 1.0e-6 1.0e-9 1.0e-12 1.0e-12 5.0e-11 1.0e-7)",
                "RDRIVE IN OUT 50",
                f"CIDC OUT 0 {capacitance_pf:.12g}e-12",
                f"LSTRAY OUT 0 {stray_inductance_nh:.12g}e-9",
                ".tran 1.0e-12 5.0e-8",
                ".control",
                "run",
                "set filetype=ascii",
                f"write {output.name} v(out)",
                ".endc",
                ".end",
            )
        )
        + "\n",
        encoding="ascii",
    )
    artifacts = {"input": str(circuit), "expected_output": str(output)}
    if include_jj:
        jj = out / "jj_check.cir"
        jj.write_text(
            "\n".join(
                (
                    "* JJ-ready transient check generated by textlayout (WRspice dialect)",
                    "* B-element + jj(level=1) model syntax per the published SNAIL-TWPA",
                    "* deck (see docs/references/jtwpa_numerical_simulations_review.md).",
                    "* Placeholder junction parameters; supply process values before use.",
                    ".model JMODEL jj(level=1) icrit=2.0e-6 cap=5.0e-14",
                    "IBIAS 0 JNODE pulse(0 1.0e-6 1.0e-9 1.0e-12 1.0e-12 1.0e-8 2.0e-8)",
                    "BJ1 JNODE 0 JMODEL",
                    f"CIDC JNODE 0 {capacitance_pf:.12g}e-12",
                    f"LSTRAY JNODE 0 {stray_inductance_nh:.12g}e-9",
                    ".tran 1.0e-12 5.0e-8",
                    ".control",
                    "run",
                    "set filetype=ascii",
                    "write jj_result.raw v(jnode)",
                    ".endc",
                    ".end",
                )
            )
            + "\n",
            encoding="ascii",
        )
        artifacts["jj_input"] = str(jj)
    manifest = out / "manifest.json"
    manifest.write_text(
        json.dumps(
            {
                "schema": "textlayout.wrspice-input.v1",
                "evidence_level": WRSPICE_INPUT_PREPARED,
                "capacitance_pf": capacitance_pf,
                "capacitance_source": capacitance_source,
                "stray_inductance_nh": stray_inductance_nh,
                "analytical_resonance_ghz": expected_ghz,
                "solver_executed": False,
                "parametric_gain_claimed": False,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    artifacts["manifest"] = str(manifest)
    return SimulationResult(
        status="input_files_prepared",
        solver="WRspice",
        readiness_level=2,
        reason="WRspice LC transient deck was generated; WRspice was not run.",
        output_dir=out,
        artifacts=artifacts,
        extracted_quantities={"analytical_resonance_ghz": expected_ghz},
        warnings=(
            f"IDC capacitance source is {capacitance_source}; WRspice is a circuit "
            "simulator and never validates the physical geometry's capacitance.",
            "The JJ-ready deck (if generated) is a syntax/readiness template, "
            "not a parametric-gain experiment.",
        ),
        evidence_level=WRSPICE_INPUT_PREPARED,
    )


def parse_wrspice_output(path: str | Path) -> Waveform:
    """Parse WRspice output: ASCII rawfile first, plain table as fallback."""
    text = Path(path).read_text(encoding="utf-8-sig")
    if "Values:" in text and "Variables:" in text:
        return _parse_ascii_rawfile(text)
    return parse_waveform_table(path)


def _parse_ascii_rawfile(text: str) -> Waveform:
    """Parse the ``set filetype=ascii`` rawfile written by ``write``."""
    lines = text.splitlines()
    names: list[str] = []
    n_variables: int | None = None
    values_start: int | None = None
    in_variables = False
    for index, raw in enumerate(lines):
        line = raw.strip()
        if line.startswith("No. Variables:"):
            n_variables = int(line.split(":", 1)[1])
        elif line.startswith("Variables:"):
            in_variables = True
        elif line.startswith("Values:"):
            values_start = index + 1
            break
        elif in_variables and line:
            parts = line.split()
            if len(parts) >= 2 and parts[0].isdigit():
                names.append(parts[1])
    if n_variables is None or values_start is None or len(names) != n_variables:
        raise ValueError("malformed WRspice ASCII rawfile header")
    numbers: list[float] = []
    for raw in lines[values_start:]:
        for token in raw.replace(",", " ").split():
            try:
                numbers.append(float(token))
            except ValueError:
                continue
    # Each point is: index, then one value per variable.
    stride = n_variables + 1
    points = len(numbers) // stride
    if points < 4:
        raise ValueError("fewer than four points in WRspice rawfile")
    columns: list[list[float]] = [[] for _ in range(n_variables)]
    for point in range(points):
        base = point * stride
        for variable in range(n_variables):
            columns[variable].append(numbers[base + 1 + variable])
    return {
        "time_s": columns[0],
        "signals": dict(zip(names[1:], columns[1:], strict=True)),
    }


def run_idc_wrspice(
    prepared: SimulationResult,
    *,
    executable: str | None = None,
    timeout_seconds: int = 600,
    resonance_tolerance_percent: float = 10.0,
) -> SimulationResult:
    """Run the LC deck in WRspice batch mode and post-process the waveform."""
    input_path = Path(prepared.artifacts.get("input", ""))
    if not input_path.is_file():
        return SimulationResult(
            status="failed",
            solver="WRspice",
            readiness_level=prepared.readiness_level,
            reason="No WRspice deck was prepared.",
            output_dir=prepared.output_dir,
            artifacts=prepared.artifacts,
            warnings=prepared.warnings,
            evidence_level="FAILED",
        )
    solver = find_wrspice(executable)
    if solver is None:
        return SimulationResult(
            status="skipped",
            solver="WRspice",
            readiness_level=2,
            reason="WRspice executable not found (checked TEXTLAYOUT_WRSPICE, "
            "wrspice, wrspice64); decks remain prepared.",
            output_dir=prepared.output_dir,
            artifacts=prepared.artifacts,
            extracted_quantities=prepared.extracted_quantities,
            warnings=prepared.warnings,
            evidence_level=SKIPPED_WRSPICE_ABSENT,
        )
    output = Path(prepared.artifacts["expected_output"])
    if output.exists():
        output.unlink()
    try:
        execution = run_subprocess(
            [solver, "-b", input_path.name],
            cwd=input_path.parent,
            timeout_seconds=timeout_seconds,
            log_prefix="wrspice",
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return SimulationResult(
            status="failed",
            solver="WRspice",
            readiness_level=2,
            reason=f"WRspice execution failed: {exc}",
            output_dir=prepared.output_dir,
            artifacts=prepared.artifacts,
            warnings=prepared.warnings,
            evidence_level="FAILED",
        )
    artifacts = {
        **prepared.artifacts,
        "solver_stdout": str(execution.stdout_path),
        "solver_stderr": str(execution.stderr_path),
    }
    base: dict[str, Any] = dict(
        solver=Path(solver).name,
        output_dir=prepared.output_dir,
        artifacts=artifacts,
        warnings=prepared.warnings,
        command=execution.command,
        return_code=execution.returncode,
        runtime_seconds=execution.runtime_seconds,
        solver_version=capture_version(solver, input_path.parent),
    )
    if execution.returncode != 0 or not output.is_file() or output.stat().st_size == 0:
        return SimulationResult(
            status="failed",
            readiness_level=2,
            reason=f"WRspice exited {execution.returncode} without non-empty waveform output.",
            evidence_level="FAILED",
            **base,
        )
    artifacts["result"] = str(output)
    try:
        transient = parse_wrspice_output(output)
    except ValueError as exc:
        return SimulationResult(
            status="executed",
            readiness_level=3,
            reason=f"WRspice ran but output parsing failed: {exc}",
            evidence_level=WRSPICE_EXECUTED,
            **base,
        )
    extracted: dict[str, Any] = {
        "sample_count": len(transient["time_s"]),
        "signal_names": list(transient["signals"]),
    }
    level = WRSPICE_TRANSIENT_PARSED
    reason = "WRspice transient output was parsed."
    expected = prepared.extracted_quantities.get("analytical_resonance_ghz")
    voltage = next(iter(transient["signals"].values()), [])
    measured = estimate_resonance_ghz(transient["time_s"], voltage)
    comparison = None
    if measured is not None and isinstance(expected, (int, float)):
        extracted["resonance_ghz"] = measured
        comparison = target_comparison(
            measured, float(expected), resonance_tolerance_percent, "resonance_ghz"
        )
        level = WRSPICE_RESONANCE_CHECKED
        reason = "WRspice transient resonance was extracted and compared with analytical LC."
    return SimulationResult(
        status="executed",
        readiness_level=4 if comparison else 3,
        reason=reason,
        extracted_quantities=extracted,
        target_comparison=comparison,
        evidence_level=level,
        **base,
    )


class WRspiceAdapter(CircuitSimulatorAdapter):
    """WRspice behind the shared circuit-simulator lifecycle."""

    name = "WRspice"
    env_var = _ENV_VAR
    executable_names = _NAMES
    tool_subdir = "wrspice"

    def prepare(self, template: LCResonanceCheck, output_dir: str | Path) -> SimulationResult:
        return prepare_idc_wrspice(
            output_dir,
            capacitance_pf=template.capacitance_pf,
            capacitance_source=template.capacitance_source,
            stray_inductance_nh=template.inductance_nh,
        )

    def run(
        self,
        prepared: SimulationResult,
        *,
        executable: str | None = None,
        timeout_seconds: int = 600,
    ) -> SimulationResult:
        return run_idc_wrspice(prepared, executable=executable, timeout_seconds=timeout_seconds)

    def parse(self, output: str | Path) -> Waveform:
        return parse_wrspice_output(output)
