"""Build the *thin* plugin bundle under `plugins/text-to-gds`.

The bundle used to be a byte-identical second copy of the whole repository --
315 duplicated modules under `plugins/text-to-gds/src/text_to_gds` alone, plus
docs, examples, benchmarks and a `uv.lock`. Every core change had to be made
twice, `ruff` and `pytest` walked both copies, and the two could drift silently
between the moment a fix landed and the moment someone remembered to re-bundle.

Nothing needed it. The plugin's `.mcp.json` launches the console script
`text-to-gds`, which resolves from the *installed* distribution -- never from a
vendored source tree. So the bundle carries only what a plugin host reads:

    plugin manifests, skills, MCP config, installation metadata, LICENSE.

`BUNDLE_ALLOWLIST` is the single source of truth for what may live there. This
script writes exactly that set and deletes everything else, and
`tests/textlayout_suite/test_plugin_thin_bundle.py` fails if a core
implementation file ever reappears.

Versions are stamped from the root `pyproject.toml` rather than hand-maintained:
they had drifted to three different values (plugin.json 0.1.0, VERSION 0.2.0,
pyproject 0.3.0) describing one artifact.

    uv run python scripts/bundle_plugin.py [--check]
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN_ROOT = ROOT / "plugins" / "text-to-gds"

#: Files copied verbatim from the repository root.
COPIED_FILES = ("LICENSE", ".mcp.json", "plugin_manifest.example.json")

#: Directories copied verbatim. `skills/` holds the agent prompts a plugin host
#: reads directly; there is no way to reference them out of the installed wheel.
COPIED_DIRS = ("skills",)

#: Manifests owned by the plugin. Only their `version` is rewritten.
MANIFESTS = (".claude-plugin/plugin.json", ".codex-plugin/plugin.json")

#: Files this script generates from the root project metadata.
GENERATED_FILES = ("VERSION", "pyproject.toml", "README.md")

#: Everything permitted under `plugins/text-to-gds`, as top-level path prefixes.
#: A path outside this set is a copied implementation file and must be removed.
BUNDLE_ALLOWLIST = frozenset(
    [*COPIED_FILES, *COPIED_DIRS, *MANIFESTS, *GENERATED_FILES, ".claude-plugin", ".codex-plugin"]
)

#: Never bundled, even from an allowlisted directory.
_IGNORED = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", ".ruff_cache")

_PYPROJECT_TEMPLATE = """\
# Generated by scripts/bundle_plugin.py -- do not edit by hand.
#
# The plugin is metadata only. It carries no source: the MCP server it exposes
# is the `text-to-gds` console script, which resolves from the installed
# distribution declared below.
[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "text-to-gds-plugin"
version = "{version}"
description = "Plugin manifest and agent skills for text-to-gds. Contains no implementation."
readme = "README.md"
requires-python = ">={requires_python}"
license = {{ text = "MIT" }}
dependencies = ["text-to-gds=={version}"]

[tool.hatch.build.targets.wheel]
only-include = ["skills"]
sources = ["."]
"""

_README_TEMPLATE = """\
<!-- Generated by scripts/bundle_plugin.py -- do not edit by hand. -->
# text-to-gds plugin

Plugin manifest and agent skills for [Text-to-Layout][repo]. **This directory
contains no implementation.**

The MCP server is the `text-to-gds` console script from the `text-to-gds`
distribution (version `{version}`), which `.mcp.json` launches. Install the
package, then point your plugin host at this directory:

```bash
pip install text-to-gds=={version}
```

| Path | Purpose |
|---|---|
| `.claude-plugin/plugin.json` | Claude Code plugin manifest |
| `.codex-plugin/plugin.json` | Codex plugin manifest |
| `.mcp.json` | MCP stdio server definition |
| `skills/` | Agent skills and prompts |
| `plugin_manifest.example.json` | Example OpenAPI plugin manifest |

Source, documentation and evidence artifacts live in the repository root. This
bundle is regenerated by `scripts/bundle_plugin.py`; edits here are overwritten.

[repo]: https://github.com/JungluChen/Text-to-Layout
"""


def _write(path: Path, content: str) -> None:
    """Write LF-terminated text regardless of platform.

    `Path.write_text` opens in text mode, so on Windows it rewrites every "\\n"
    as "\\r\\n". The generated files would then differ from their committed LF
    form and CI's `git diff --exit-code -- plugins/text-to-gds` would fail for a
    Windows contributor who had merely re-run the bundler.
    """
    path.write_text(content, encoding="utf-8", newline="\n")


def _project_metadata() -> tuple[str, str]:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    project = data["project"]
    requires_python = str(project.get("requires-python", ">=3.11")).lstrip(">=")
    return str(project["version"]), requires_python


def _expected_paths() -> set[Path]:
    """Every file the bundle should contain, relative to the plugin root."""
    expected = {Path(name) for name in (*COPIED_FILES, *GENERATED_FILES, *MANIFESTS)}
    for dirname in COPIED_DIRS:
        source = ROOT / dirname
        for path in source.rglob("*"):
            if path.is_file() and "__pycache__" not in path.parts:
                expected.add(Path(dirname) / path.relative_to(source))
    return expected


def _stray_paths() -> list[Path]:
    """Files present in the bundle that the allowlist does not permit."""
    if not PLUGIN_ROOT.is_dir():
        return []
    strays = []
    for path in PLUGIN_ROOT.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(PLUGIN_ROOT)
        if relative.parts[0] in {"__pycache__", ".ruff_cache", ".pytest_cache"}:
            continue
        if relative.parts[0] not in BUNDLE_ALLOWLIST:
            strays.append(relative)
    return sorted(strays)


def _stamp_version(relative: str, version: str) -> None:
    """Rewrite only the `version` field, preserving the hand-maintained rest."""
    path = PLUGIN_ROOT / relative
    if not path.is_file():
        raise SystemExit(f"missing plugin manifest: {path}")
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("version") == version:
        return
    manifest["version"] = version
    _write(path, json.dumps(manifest, indent=2) + "\n")


def build() -> None:
    version, requires_python = _project_metadata()

    for relative in _stray_paths():
        (PLUGIN_ROOT / relative).unlink()
    for directory in PLUGIN_ROOT.iterdir() if PLUGIN_ROOT.is_dir() else ():
        if directory.is_dir() and directory.name not in BUNDLE_ALLOWLIST:
            shutil.rmtree(directory)

    PLUGIN_ROOT.mkdir(parents=True, exist_ok=True)
    for name in COPIED_FILES:
        shutil.copy2(ROOT / name, PLUGIN_ROOT / name)
    for dirname in COPIED_DIRS:
        destination = PLUGIN_ROOT / dirname
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(ROOT / dirname, destination, ignore=_IGNORED)

    _write(PLUGIN_ROOT / "VERSION", f"{version}\n")
    _write(
        PLUGIN_ROOT / "pyproject.toml",
        _PYPROJECT_TEMPLATE.format(version=version, requires_python=requires_python),
    )
    _write(PLUGIN_ROOT / "README.md", _README_TEMPLATE.format(version=version))
    for manifest in MANIFESTS:
        _stamp_version(manifest, version)


def check() -> int:
    """Report, without writing, whether the bundle is thin and current."""
    problems = [f"copied implementation file in plugin bundle: {p}" for p in _stray_paths()]
    version, _ = _project_metadata()
    for manifest in MANIFESTS:
        path = PLUGIN_ROOT / manifest
        if not path.is_file():
            problems.append(f"missing plugin manifest: {manifest}")
            continue
        declared = json.loads(path.read_text(encoding="utf-8")).get("version")
        if declared != version:
            problems.append(f"{manifest} declares version {declared!r}, project is {version!r}")
    for relative in sorted(_expected_paths()):
        if not (PLUGIN_ROOT / relative).is_file():
            problems.append(f"missing bundled file: {relative}")
    for problem in problems:
        print(f"[FAIL] {problem}", file=sys.stderr)
    if problems:
        print(
            f"\n{len(problems)} problem(s). Run 'python scripts/bundle_plugin.py' and commit.",
            file=sys.stderr,
        )
        return 1
    print(f"plugin bundle is thin and current ({version}).")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args(argv)
    if args.check:
        return check()
    build()
    print(f"Bundled thin plugin at {PLUGIN_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
