"""Enforce the textlayout / text_to_gds namespace boundary (strangler-fig).

`textlayout` is the supported implementation namespace; `text_to_gds` is the
frozen legacy MCP surface (see docs/ARCHITECTURE.md). This guard makes the
consolidation *mechanical* rather than a convention people remember:

1. **Inward-only boundary.** No module under ``src/textlayout`` may import
   ``text_to_gds``. The product path must never depend on the legacy package,
   so the legacy package can be retired module by module without touching it.

2. **Shim-only legacy package.** Every Python file under ``src/text_to_gds``
   must be either the deprecation infrastructure or a structural shim. There
   is no grandfathered implementation baseline: implementation belongs under
   ``src/textlayout``.

Run ``--check`` (the CI default) to verify, or ``--update`` to re-pin the
manifest after a deliberate, reviewed change. Mirrors the committed-manifest +
``--check`` pattern already used by ``scripts/bundle_plugin.py``.

    uv run python scripts/check_namespace_boundary.py [--check | --update]
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEXTLAYOUT_SRC = ROOT / "src" / "textlayout"
LEGACY_SRC = ROOT / "src" / "text_to_gds"
MANIFEST = ROOT / "scripts" / "text_to_gds_freeze_manifest.txt"

#: The legacy package the product must never import.
FORBIDDEN_IMPORT_ROOT = "text_to_gds"

#: Structural marker a module sets (directly or via ``deprecated_reexport``) to
#: declare itself a thin re-export shim rather than legacy implementation.
SHIM_MARKER = "__textlayout_shim__"

#: Non-shim files allowed because they implement deprecation infrastructure.
INFRASTRUCTURE_ALLOW = frozenset({"_deprecation.py"})


def _iter_py(base: Path) -> list[Path]:
    return sorted(p for p in base.rglob("*.py") if "__pycache__" not in p.parts)


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def boundary_violations() -> list[tuple[str, str]]:
    """Return ``(file, statement)`` for every textlayout import of the legacy package."""
    violations: list[tuple[str, str]] = []
    for path in _iter_py(TEXTLAYOUT_SRC):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if _is_forbidden(alias.name):
                        violations.append((_rel(path), f"import {alias.name}"))
            elif isinstance(node, ast.ImportFrom):
                # Absolute imports only; textlayout uses no relative escape to a
                # sibling top-level package, so level>0 can never reach it.
                if node.level == 0 and node.module and _is_forbidden(node.module):
                    violations.append((_rel(path), f"from {node.module} import ..."))
    return violations


def _is_forbidden(dotted: str) -> bool:
    return dotted == FORBIDDEN_IMPORT_ROOT or dotted.startswith(FORBIDDEN_IMPORT_ROOT + ".")


def is_shim_source(source: str) -> bool:
    """True if the module declares itself a re-export shim (structural, no import)."""
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return False
    for node in ast.walk(tree):
        # Direct marker assignment: ``__textlayout_shim__ = True``.
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == SHIM_MARKER:
                    return True
        # Or a call to the shim helper, which sets the marker for the module.
        if isinstance(node, ast.Call):
            func = node.func
            name = getattr(func, "attr", None) or getattr(func, "id", None)
            if name == "deprecated_reexport":
                return True
    return False


def freeze_violations() -> list[str]:
    """Return every non-shim implementation file in the legacy package."""
    violations: list[str] = []
    for path in _iter_py(LEGACY_SRC):
        rel = _rel(path)
        if path.name in INFRASTRUCTURE_ALLOW:
            continue
        if is_shim_source(path.read_text(encoding="utf-8")):
            continue
        violations.append(rel)
    return violations


def write_manifest() -> int:
    """Write the intentionally empty implementation manifest."""
    files: list[str] = []
    header = (
        "# No implementation files are allowed under src/text_to_gds.\n"
        "# Generated by scripts/check_namespace_boundary.py --update.\n"
        "# Only structural deprecation shims and _deprecation.py are permitted.\n"
    )
    MANIFEST.write_text(header + "\n".join(sorted(files)) + "\n", encoding="utf-8")
    return len(files)


def check() -> int:
    ok = True
    boundary = boundary_violations()
    if boundary:
        ok = False
        print("::error:: textlayout must not import the legacy text_to_gds package:")
        for file, stmt in boundary:
            print(f"  {file}: {stmt}")
    freeze = freeze_violations()
    if freeze:
        ok = False
        print("::error:: new non-shim implementation file(s) added to frozen text_to_gds:")
        for rel in freeze:
            print(f"  {rel}")
        print(
            "  New features belong in src/textlayout. To retire a legacy module, replace it\n"
            "  with a deprecated_reexport() shim; to intentionally re-pin the baseline run\n"
            "  scripts/check_namespace_boundary.py --update."
        )
    if ok:
        print("namespace boundary OK: textlayout imports no legacy code; legacy package frozen.")
    return 0 if ok else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="verify the boundary (default)")
    group.add_argument("--update", action="store_true", help="re-pin the freeze manifest")
    args = parser.parse_args(argv)
    if args.update:
        count = write_manifest()
        print(f"re-pinned {_rel(MANIFEST)} with {count} legacy implementation files")
        return 0
    return check()


if __name__ == "__main__":
    sys.exit(main())
