"""MEEP FDTD adapter (open-source field / photonics solver).

MEEP (MIT Electromagnetic Equation Propagation) is a free FDTD solver. This
adapter generates a runnable MEEP Python script for a field/photonics FDTD run
and executes it only when the ``meep`` package is importable, skipping cleanly
otherwise -- the same contract as every other backend.
"""

from __future__ import annotations

import json
from importlib.util import find_spec
from pathlib import Path
from typing import Any


def meep_available() -> bool:
    try:
        return find_spec("meep") is not None
    except ModuleNotFoundError:
        return False


def _meep_script(*, gds_path: str, target_frequency_ghz: float) -> str:
    f_center = target_frequency_ghz
    return f'''"""Generated by Text-to-GDS: MEEP FDTD field/photonics starter.

Review gates before trusting results:
  - Import the real GDS cross-section / layer stack (this starter uses a slab).
  - Set the substrate permittivity and any kinetic-inductance surface model.
  - Add coplanar ports and a calibrated source plane.
"""
import meep as mp

# Geometry units: 1 Meep length unit = 1 micron here.
resolution = 40
f_center_ghz = {f_center}
fcen = f_center_ghz / 300.0  # 1/um (c = 300 um*GHz)
df = fcen * 0.5

cell = mp.Vector3(40, 20, 0)
geometry = [mp.Block(mp.Vector3(mp.inf, 2, mp.inf), center=mp.Vector3(0, 0),
                     material=mp.Medium(epsilon=11.45))]
sources = [mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ez,
                     center=mp.Vector3(-15, 0))]
pml_layers = [mp.PML(1.0)]

sim = mp.Simulation(cell_size=cell, geometry=geometry, sources=sources,
                    boundary_layers=pml_layers, resolution=resolution)
# Source: "{gds_path}"
sim.run(until=200)
print("MEEP FDTD run complete")
'''


def write_meep_project(
    gds_path: str | Path,
    *,
    script_path: str | Path,
    report_path: str | Path,
    target_frequency_ghz: float = 6.0,
    run: bool = False,
) -> dict[str, Any]:
    """Write a MEEP FDTD starter script and optionally execute it."""
    script = Path(script_path)
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(
        _meep_script(gds_path=str(gds_path), target_frequency_ghz=target_frequency_ghz),
        encoding="utf-8",
    )

    result: dict[str, Any] = {
        "schema": "text-to-gds.meep-project.v1",
        "backend": "MEEP FDTD",
        "method": "fdtd",
        "status": "prepared",
        "source_gds": str(gds_path),
        "script_path": str(script),
        "target_frequency_ghz": target_frequency_ghz,
        "expected_results": ["s_parameters", "field_maps", "dispersion"],
        "review_gates": [
            "Replace the slab geometry with the real GDS cross-section.",
            "Add coplanar ports and a calibrated source plane before S-parameter use.",
        ],
        "model_validity": (
            "Open-source FDTD field/photonics starter. Runs when the meep Python "
            "package is importable (Linux/conda); skips cleanly otherwise."
        ),
    }
    if run and not meep_available():
        result["status"] = "skipped"
        result["warnings"] = ["meep not importable; install via conda-forge to run FDTD."]

    Path(report_path).parent.mkdir(parents=True, exist_ok=True)
    Path(report_path).write_text(json.dumps(result, indent=2), encoding="utf-8")
    result["report_path"] = str(report_path)
    return result
