"""PyAEDT project generation and normalized EM-result feedback."""

from __future__ import annotations

import json
import math
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

from textlayout._legacy.process import DEFAULT_PROCESS


HFSS_SCRIPT = r'''# Generated by Text-to-GDS for PyAEDT 1.1+.
from __future__ import annotations

import argparse
import cmath
import json
import math
import shutil
import traceback
from pathlib import Path

from ansys.aedt.core import Hfss


CONFIG_PATH = Path(r"__CONFIG_PATH__")


def load_config():
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def write_json(path, payload):
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def layer_map(config):
    return {
        int(number): [
            (float(spec["elevation_um"]), float(spec["thickness_um"])),
            spec["name"],
        ]
        for number, spec in config["layer_mapping"].items()
    }


def add_materials(app, config):
    for material in config["solver_materials"]:
        name = material["name"]
        if name.casefold() in app.materials.material_keys:
            continue
        created = app.materials.add_material(name)
        if material.get("relative_permittivity") is not None:
            created.permittivity = float(material["relative_permittivity"])
        if material.get("loss_tangent") is not None:
            created.dielectric_loss_tangent = float(material["loss_tangent"])
        if material.get("conductivity_s_per_m") is not None:
            created.conductivity = float(material["conductivity_s_per_m"])


def configure_geometry(app, config, add_radiation):
    app.modeler.model_units = "um"
    imported_before = set(app.modeler.object_names)
    app.import_gds_3d(
        config["source_gds"],
        layer_map(config),
        units="um",
        import_method=1,
    )
    imported = [name for name in app.modeler.object_names if name not in imported_before]
    add_materials(app, config)

    for object_name in imported:
        lower_name = object_name.lower()
        for spec in config["layer_mapping"].values():
            if spec["name"].lower() in lower_name:
                app.modeler[object_name].material_name = spec["hfss_material"]
                break

    bbox = config["bbox_um"]
    substrate = config["substrate"]
    margin = float(substrate["lateral_margin_um"])
    thickness = float(substrate["thickness_um"])
    substrate_box = app.modeler.create_box(
        [bbox[0] - margin, bbox[1] - margin, -thickness],
        [bbox[2] - bbox[0] + 2 * margin, bbox[3] - bbox[1] + 2 * margin, thickness],
        name="TextToGDS_Substrate",
        material=substrate["material_name"],
    )
    if add_radiation:
        region = app.modeler.create_air_region(50, 50, 100, 50, 50, 20, is_percentage=True)
        app.assign_radiation_boundary_to_objects(region, name="OpenBoundary")
    return imported, substrate_box.name


def create_ports(app, config):
    created = []
    z_bottom = -float(config["ports"]["sheet_below_metal_um"])
    sheet_height = float(config["ports"]["sheet_height_um"])
    gap = float(config["ports"]["cpw_gap_um"])
    for index, port in enumerate(config["ports"]["items"], start=1):
        x, y = [float(value) for value in port["center"]]
        conductor_width = max(float(port.get("width", 10.0)), 0.1)
        span = max(conductor_width + 6.0 * gap, conductor_width * 3.0)
        orientation = int(round(float(port.get("orientation") or 0.0))) % 360
        safe_name = "".join(ch if ch.isalnum() else "_" for ch in port["name"])
        if orientation in (0, 180):
            sheet = app.modeler.create_rectangle(
                "YZ", [x, y - span / 2.0, z_bottom], [span, sheet_height],
                name=f"PortSheet_{safe_name}",
            )
            line = [[x, y, 0.0], [x, y + 0.45 * span, 0.0]]
        else:
            sheet = app.modeler.create_rectangle(
                "XZ", [x - span / 2.0, y, z_bottom], [span, sheet_height],
                name=f"PortSheet_{safe_name}",
            )
            line = [[x, y, 0.0], [x + 0.45 * span, y, 0.0]]
        boundary = app.lumped_port(
            sheet.name,
            integration_line=line,
            impedance=50,
            name=port["name"] or f"Port{index}",
        )
        created.append(boundary.name)
    return created


def export_fields(app, config, imported_objects, setup_sweep):
    outputs = {}
    frequency = f'{config["analysis"]["frequency_ghz"]:g}GHz'
    quantities = {
        "electric_field": ("Mag_E", config["outputs"]["electric_field_png"], "volume"),
        "magnetic_field": ("Mag_H", config["outputs"]["magnetic_field_png"], "volume"),
        "current_density": ("Mag_Jsurf", config["outputs"]["current_density_png"], "surface"),
    }
    for label, (quantity, path, plot_kind) in quantities.items():
        try:
            if plot_kind == "surface":
                plot = app.post.create_fieldplot_surface(
                    imported_objects,
                    quantity,
                    setup=setup_sweep,
                    intrinsics={"Freq": frequency, "Phase": "0deg"},
                    plot_name=f"TextToGDS_{label}",
                )
            else:
                plot = app.post.create_fieldplot_volume(
                    imported_objects,
                    quantity,
                    setup=setup_sweep,
                    intrinsics={"Freq": frequency, "Phase": "0deg"},
                    plot_name=f"TextToGDS_{label}",
                )
            exported = plot.export_image(path, orientation="top", show_region=False) if plot else False
            outputs[label] = str(exported) if exported else None
        except Exception as exc:
            outputs[label] = None
            outputs[f"{label}_error"] = str(exc)
    return outputs


def summarize_touchstone(path):
    source = Path(path)
    if not source.exists():
        return None
    scale = 1.0
    data_format = "MA"
    rows = []
    for raw_line in source.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("!"):
            continue
        if line.startswith("#"):
            tokens = line[1:].upper().split()
            scale = {"HZ": 1e-9, "KHZ": 1e-6, "MHZ": 1e-3, "GHZ": 1.0}.get(tokens[0], 1.0)
            data_format = next((item for item in ("RI", "MA", "DB") if item in tokens), "MA")
            continue
        values = [float(value) for value in line.split()]
        if len(values) >= 9:
            rows.append(values)
    if not rows:
        return None

    def pair_to_complex(a, b):
        if data_format == "RI":
            return complex(a, b)
        phase = math.radians(b)
        magnitude = 10.0 ** (a / 20.0) if data_format == "DB" else a
        return cmath.rect(magnitude, phase)

    frequencies = [row[0] * scale for row in rows]
    s21 = [abs(pair_to_complex(row[3], row[4])) for row in rows]
    notch_index = min(range(len(s21)), key=s21.__getitem__)
    peak_index = max(range(len(s21)), key=s21.__getitem__)
    return {
        "points": len(rows),
        "frequency_start_ghz": frequencies[0],
        "frequency_stop_ghz": frequencies[-1],
        "s21_notch_frequency_ghz": frequencies[notch_index],
        "s21_notch_db": 20.0 * math.log10(max(s21[notch_index], 1e-30)),
        "s21_peak_frequency_ghz": frequencies[peak_index],
        "s21_peak_db": 20.0 * math.log10(max(s21[peak_index], 1e-30)),
    }


def eigenmode_results(app, setup_name):
    solution_name = f"{setup_name} : LastAdaptive"
    quantities = app.post.available_report_quantities(
        report_category="Eigenmode Parameters",
        display_type="Data Table",
        solution=solution_name,
    )
    result = {"available_quantities": quantities, "values": {}}
    if not quantities:
        return result
    data = app.post.get_solution_data(
        expressions=quantities,
        setup_sweep_name=solution_name,
        report_category="Eigenmode Parameters",
    )
    for expression in getattr(data, "expressions", quantities):
        try:
            result["values"][expression] = [float(value) for value in data.data_real(expression)]
        except Exception as exc:
            result["values"][expression] = {"error": str(exc)}
    try:
        result["primary_sweep_values"] = [float(value) for value in data.primary_sweep_values]
    except Exception:
        pass
    return result


def main():
    parser = argparse.ArgumentParser(description="Build Text-to-GDS HFSS projects through PyAEDT.")
    parser.add_argument("--solve", action="store_true", help="Run AEDT solves and export result artifacts.")
    parser.add_argument("--overwrite", action="store_true", help="Replace an existing AEDT project.")
    parser.add_argument("--non-graphical", action="store_true")
    parser.add_argument("--version", default=None, help="AEDT version, for example 2025.2 or 252.")
    args = parser.parse_args()
    config = load_config()
    project_path = Path(config["outputs"]["hfss_project"])
    result_path = Path(config["outputs"]["hfss_results_json"])
    result = {
        "schema": "text-to-gds.pyaedt-hfss-results.v1",
        "status": "building",
        "config_path": str(CONFIG_PATH),
        "project_path": str(project_path),
        "solved": False,
    }
    if project_path.exists():
        if not args.overwrite:
            raise FileExistsError(f"Project exists; pass --overwrite: {project_path}")
        project_path.unlink()
    lock = Path(str(project_path) + ".lock")
    if lock.exists() and args.overwrite:
        lock.unlink()

    driven = None
    eigen = None
    try:
        driven = Hfss(
            project=str(project_path),
            design="HFSS_Driven",
            solution_type="Modal",
            version=args.version,
            non_graphical=args.non_graphical,
            new_desktop=True,
            close_on_exit=False,
        )
        imported, _ = configure_geometry(driven, config, add_radiation=True)
        ports = create_ports(driven, config)
        setup = driven.create_setup(name="DrivenSetup")
        setup.props["Frequency"] = f'{config["analysis"]["frequency_ghz"]:g}GHz'
        setup.props["MaximumPasses"] = int(config["analysis"]["maximum_passes"])
        setup.props["MaxDeltaS"] = float(config["analysis"]["max_delta_s"])
        setup.update()
        driven.create_linear_count_sweep(
            setup="DrivenSetup",
            unit="GHz",
            start_frequency=float(config["analysis"]["sweep_start_ghz"]),
            stop_frequency=float(config["analysis"]["sweep_stop_ghz"]),
            num_of_freq_points=int(config["analysis"]["sweep_points"]),
            name="Sweep1",
            save_fields=True,
            sweep_type="Interpolating",
        )
        driven.save_project(str(project_path))
        result["ports"] = ports

        if args.solve:
            if len(ports) < 2:
                raise RuntimeError("Driven-modal solve requires at least two reviewed RF ports.")
            driven.analyze_setup("DrivenSetup")
            touchstone = driven.export_touchstone(
                setup="DrivenSetup",
                sweep="Sweep1",
                output_file=config["outputs"]["touchstone_s2p"],
            )
            result["touchstone_s2p"] = str(touchstone)
            result["s_parameters"] = summarize_touchstone(config["outputs"]["touchstone_s2p"])
            result["field_images"] = export_fields(
                driven, config, imported, "DrivenSetup : Sweep1"
            )

        eigen = Hfss(
            project=str(project_path),
            design="HFSS_Eigenmode",
            solution_type="Eigenmode",
            version=args.version,
            non_graphical=args.non_graphical,
            new_desktop=False,
            close_on_exit=False,
        )
        configure_geometry(eigen, config, add_radiation=True)
        eigen_setup = eigen.create_setup(name="EigenSetup")
        eigen_setup.props["MinimumFrequency"] = (
            f'{config["analysis"]["eigen_min_frequency_ghz"]:g}GHz'
        )
        eigen_setup.props["NumModes"] = int(config["analysis"]["eigen_modes"])
        eigen_setup.props["MaximumPasses"] = int(config["analysis"]["maximum_passes"])
        eigen_setup.update()
        eigen.save_project(str(project_path))
        if args.solve:
            eigen.analyze_setup("EigenSetup")
            result["eigenmodes"] = eigenmode_results(eigen, "EigenSetup")
            write_json(config["outputs"]["eigenmode_json"], result["eigenmodes"])
            result["solved"] = True

        eigen.save_project(str(project_path))
        result["status"] = "solved" if args.solve else "built"
    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        result["traceback"] = traceback.format_exc()
        write_json(result_path, result)
        raise
    finally:
        active = eigen or driven
        if active is not None:
            try:
                active.release_desktop(close_projects=True, close_desktop=True)
            except Exception:
                pass
    write_json(result_path, result)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
'''


Q3D_SCRIPT = r'''# Generated by Text-to-GDS for PyAEDT 1.1+.
from __future__ import annotations

import argparse
import csv
import json
import traceback
from pathlib import Path

from ansys.aedt.core import Q3d


CONFIG_PATH = Path(r"__CONFIG_PATH__")


def load_config():
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def write_json(path, payload):
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def layer_map(config):
    return {
        int(number): [
            (float(spec["elevation_um"]), float(spec["thickness_um"])),
            spec["name"],
        ]
        for number, spec in config["layer_mapping"].items()
    }


def add_materials(app, config):
    for material in config["solver_materials"]:
        name = material["name"]
        if name.casefold() in app.materials.material_keys:
            continue
        created = app.materials.add_material(name)
        if material.get("relative_permittivity") is not None:
            created.permittivity = float(material["relative_permittivity"])
        if material.get("loss_tangent") is not None:
            created.dielectric_loss_tangent = float(material["loss_tangent"])
        if material.get("conductivity_s_per_m") is not None:
            created.conductivity = float(material["conductivity_s_per_m"])


def configure_geometry(app, config):
    app.modeler.model_units = "um"
    before = set(app.modeler.object_names)
    app.import_gds_3d(config["source_gds"], layer_map(config), units="um", import_method=1)
    imported = [name for name in app.modeler.object_names if name not in before]
    add_materials(app, config)
    for object_name in imported:
        lower_name = object_name.lower()
        for spec in config["layer_mapping"].values():
            if spec["name"].lower() in lower_name:
                app.modeler[object_name].material_name = spec["q3d_material"]
                break
    bbox = config["bbox_um"]
    substrate = config["substrate"]
    margin = float(substrate["lateral_margin_um"])
    thickness = float(substrate["thickness_um"])
    app.modeler.create_box(
        [bbox[0] - margin, bbox[1] - margin, -thickness],
        [bbox[2] - bbox[0] + 2 * margin, bbox[3] - bbox[1] + 2 * margin, thickness],
        name="TextToGDS_Substrate",
        material=substrate["material_name"],
    )
    return imported


def numeric_matrix_summary(path):
    source = Path(path)
    if not source.exists():
        return None
    rows = []
    for row in csv.reader(source.open(encoding="utf-8", errors="ignore")):
        numeric = []
        for value in row:
            try:
                numeric.append(float(value.strip()))
            except ValueError:
                continue
        if len(numeric) >= 2:
            rows.append(numeric)
    width = max((len(row) for row in rows), default=0)
    square = [row[-width:] for row in rows if len(row) >= width]
    return {"numeric_rows": len(rows), "maximum_numeric_columns": width, "matrix": square}


def main():
    parser = argparse.ArgumentParser(description="Build Text-to-GDS Q3D extraction through PyAEDT.")
    parser.add_argument("--solve", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--non-graphical", action="store_true")
    parser.add_argument("--version", default=None)
    args = parser.parse_args()
    config = load_config()
    project_path = Path(config["outputs"]["q3d_project"])
    result_path = Path(config["outputs"]["q3d_results_json"])
    result = {
        "schema": "text-to-gds.pyaedt-q3d-results.v1",
        "status": "building",
        "config_path": str(CONFIG_PATH),
        "project_path": str(project_path),
        "solved": False,
    }
    if project_path.exists():
        if not args.overwrite:
            raise FileExistsError(f"Project exists; pass --overwrite: {project_path}")
        project_path.unlink()
    lock = Path(str(project_path) + ".lock")
    if lock.exists() and args.overwrite:
        lock.unlink()

    app = None
    try:
        app = Q3d(
            project=str(project_path),
            design="Q3D_Extractor",
            version=args.version,
            non_graphical=args.non_graphical,
            new_desktop=True,
            close_on_exit=False,
        )
        imported = configure_geometry(app, config)
        app.auto_identify_nets()
        setup = app.create_setup(
            name="Q3DSetup",
            AdaptiveFreq=f'{config["analysis"]["frequency_ghz"]:g}GHz',
        )
        app.save_project(str(project_path))
        result["imported_objects"] = imported
        result["nets"] = list(app.net_names)
        if args.solve:
            if not app.net_names:
                raise RuntimeError("Q3D found no conductor nets; review layer material mapping.")
            app.analyze_setup(setup.name)
            matrix_path = config["outputs"]["q3d_matrix_csv"]
            exported = app.export_matrix_data(
                matrix_path,
                problem_type="C",
                setup=setup.name,
                c_unit="pF",
                matrix_type="Maxwell, Couple",
            )
            if not exported:
                raise RuntimeError("Q3D matrix export failed.")
            result["capacitance_matrix_csv"] = matrix_path
            result["capacitance_matrix"] = numeric_matrix_summary(matrix_path)
            result["solved"] = True
        app.save_project(str(project_path))
        result["status"] = "solved" if args.solve else "built"
    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)
        result["traceback"] = traceback.format_exc()
        write_json(result_path, result)
        raise
    finally:
        if app is not None:
            try:
                app.release_desktop(close_projects=True, close_desktop=True)
            except Exception:
                pass
    write_json(result_path, result)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
'''


def _load_mapping(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    with source.open(encoding="utf-8") as stream:
        data = yaml.safe_load(stream)
    if not isinstance(data, dict):
        raise ValueError(f"Expected a mapping in {source}")
    return data


def _default_sidecar(gds_path: Path) -> dict[str, Any]:
    return {
        "schema": "text-to-gds.sidecar.v0",
        "gds_path": str(gds_path),
        "bbox_um": [[-500.0, -500.0], [500.0, 500.0]],
        "ports": [],
        "info": {},
        "process_stack": DEFAULT_PROCESS.to_dict(),
    }


def _normalized_bbox(sidecar: dict[str, Any]) -> list[float]:
    bbox = sidecar.get("bbox_um")
    if (
        isinstance(bbox, list)
        and len(bbox) == 2
        and all(isinstance(point, list) and len(point) >= 2 for point in bbox)
    ):
        return [float(bbox[0][0]), float(bbox[0][1]), float(bbox[1][0]), float(bbox[1][1])]
    return [-500.0, -500.0, 500.0, 500.0]


def _layer_mapping(process_stack: dict[str, Any]) -> tuple[dict[str, Any], list[str]]:
    layers = process_stack.get("layers")
    if not isinstance(layers, dict) or not layers:
        raise ValueError("Process stack must define a non-empty layers mapping")
    mapping: dict[str, Any] = {}
    warnings: list[str] = []
    elevation_um = 0.0
    for fallback_name, raw_spec in layers.items():
        if not isinstance(raw_spec, dict):
            continue
        name = str(raw_spec.get("name") or fallback_name)
        layer = raw_spec.get("layer")
        if not isinstance(layer, (list, tuple)) or not layer:
            warnings.append(f"Skipped {name}: missing GDS layer number")
            continue
        thickness_um = float(raw_spec.get("thickness_um", 0.0))
        if not thickness_um:
            thickness_um = float(raw_spec.get("thickness_nm", 0.0)) / 1000.0
        if thickness_um <= 0:
            warnings.append(f"Skipped {name}: non-positive physical thickness")
            continue
        layer_number = str(int(layer[0]))
        if layer_number in mapping:
            raise ValueError(
                f"PyAEDT GDS import cannot distinguish duplicate layer number {layer_number}"
            )
        material = str(raw_spec.get("material") or "unknown")
        mapping[layer_number] = {
            "name": name,
            "datatype": int(layer[1]) if len(layer) > 1 else 0,
            "elevation_um": elevation_um,
            "thickness_um": thickness_um,
            "process_material": material,
            "hfss_material": "pec" if material.lower() in {"nb", "al", "tin", "nbtin"} else "vacuum",
            "q3d_material": "copper" if material.lower() in {"nb", "al", "tin", "nbtin"} else "vacuum",
        }
        elevation_um += thickness_um
    if not mapping:
        raise ValueError("No positive-thickness GDS layers were available for PyAEDT")
    return mapping, warnings


def _solver_materials(
    process_stack: dict[str, Any], em_process: dict[str, Any]
) -> list[dict[str, Any]]:
    materials = process_stack.get("materials") or {}
    result: list[dict[str, Any]] = []
    for name, raw in materials.items():
        if not isinstance(raw, dict) or raw.get("relative_permittivity") is None:
            continue
        result.append(
            {
                "name": f"TextToGDS_{name}",
                "relative_permittivity": float(raw["relative_permittivity"]),
                "loss_tangent": float(raw.get("loss_tangent", 0.0)),
                "conductivity_s_per_m": raw.get("conductivity_s_per_m"),
            }
        )
    substrate = em_process.get("substrate") or {}
    result.append(
        {
            "name": str(substrate.get("material_name", "TextToGDS_HR_Silicon")),
            "relative_permittivity": float(substrate.get("relative_permittivity", 11.45)),
            "loss_tangent": float(substrate.get("loss_tangent", 1e-6)),
            "conductivity_s_per_m": substrate.get("conductivity_s_per_m"),
        }
    )
    return result


def build_pyaedt_config(
    gds_path: str | Path,
    *,
    outputs: dict[str, str],
    sidecar_path: str | Path | None = None,
    process_path: str | Path | None = None,
    setup_frequency_ghz: float = 6.0,
    sweep_start_ghz: float = 1.0,
    sweep_stop_ghz: float = 12.0,
    sweep_points: int = 221,
) -> dict[str, Any]:
    """Build the explicit GDS/process/port contract consumed by generated PyAEDT scripts."""
    gds = Path(gds_path).resolve()
    sidecar = _load_mapping(sidecar_path) if sidecar_path else _default_sidecar(gds)
    em_process = _load_mapping(process_path) if process_path else {}
    process_stack = em_process.get("process_stack") or sidecar.get("process_stack")
    if not isinstance(process_stack, dict):
        process_stack = DEFAULT_PROCESS.to_dict()
    mapping, warnings = _layer_mapping(process_stack)
    process_materials = process_stack.get("materials") or {}
    for spec in mapping.values():
        material_name = spec["process_material"]
        material = process_materials.get(material_name) or {}
        if material.get("relative_permittivity") is not None:
            solver_name = f"TextToGDS_{material_name}"
            spec["hfss_material"] = solver_name
            spec["q3d_material"] = solver_name
    substrate_overrides = em_process.get("substrate") or {}
    substrate = {
        "material_name": str(
            substrate_overrides.get("material_name", "TextToGDS_HR_Silicon")
        ),
        "relative_permittivity": float(
            substrate_overrides.get("relative_permittivity", 11.45)
        ),
        "loss_tangent": float(substrate_overrides.get("loss_tangent", 1e-6)),
        "conductivity_s_per_m": substrate_overrides.get("conductivity_s_per_m"),
        "thickness_um": float(substrate_overrides.get("thickness_um", 500.0)),
        "lateral_margin_um": float(substrate_overrides.get("lateral_margin_um", 100.0)),
    }
    all_ports = [item for item in sidecar.get("ports", []) if isinstance(item, dict)]
    rf_ports = [item for item in all_ports if "rf" in str(item.get("name", "")).lower()]
    ports = rf_ports or all_ports[:2]
    stack_height = max(
        float(spec["elevation_um"]) + float(spec["thickness_um"])
        for spec in mapping.values()
    )
    cpw_gap = float((sidecar.get("info") or {}).get("cpw_gap_um", 6.0))
    return {
        "schema": "text-to-gds.pyaedt-config.v1",
        "source_gds": str(gds),
        "source_sidecar": str(Path(sidecar_path).resolve()) if sidecar_path else None,
        "source_process": str(Path(process_path).resolve()) if process_path else None,
        "bbox_um": _normalized_bbox(sidecar),
        "layer_mapping": mapping,
        "solver_materials": _solver_materials(process_stack, {"substrate": substrate}),
        "substrate": substrate,
        "ports": {
            "items": ports,
            "cpw_gap_um": cpw_gap,
            "sheet_below_metal_um": max(5.0, substrate["thickness_um"] * 0.02),
            "sheet_height_um": max(20.0, stack_height + 10.0),
            "review_required": True,
        },
        "analysis": {
            "frequency_ghz": float(setup_frequency_ghz),
            "sweep_start_ghz": float(sweep_start_ghz),
            "sweep_stop_ghz": float(sweep_stop_ghz),
            "sweep_points": int(sweep_points),
            "maximum_passes": 12,
            "max_delta_s": 0.02,
            "eigen_min_frequency_ghz": max(0.1, float(setup_frequency_ghz) * 0.5),
            "eigen_modes": 4,
        },
        "outputs": outputs,
        "warnings": warnings,
        "validity": {
            "geometry": "GDS layers are imported with explicit elevations and thicknesses.",
            "ports": "Generated lumped-port sheets must be reviewed against the CPW ground geometry.",
            "metals": "Default Nb/Al/TiN handling is PEC in HFSS and copper in Q3D.",
            "loss": "Replace placeholder substrate loss and conductor models before loss/Q signoff.",
        },
    }


def _write_script(template: str, config_path: Path, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rendered = template.replace("__CONFIG_PATH__", str(config_path.resolve()))
    output_path.write_text(rendered, encoding="utf-8")


def _execute_script(
    script_path: Path, *, solve: bool, timeout_seconds: int = 3600
) -> dict[str, Any]:
    command = [sys.executable, str(script_path), "--overwrite"]
    if solve:
        command.append("--solve")
    try:
        completed = subprocess.run(
            command, capture_output=True, text=True, check=False, timeout=timeout_seconds
        )
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout.decode(errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode(errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return {
            "command": command,
            "returncode": None,
            "stdout": stdout,
            "stderr": stderr + f"\n[text-to-gds] AEDT script timed out after {timeout_seconds} s.",
        }
    return {
        "command": command,
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def write_pyaedt_project_bundle(
    gds_path: str | Path,
    *,
    config_path: str | Path,
    hfss_script_path: str | Path,
    q3d_script_path: str | Path,
    report_path: str | Path,
    hfss_project_path: str | Path,
    q3d_project_path: str | Path,
    sidecar_path: str | Path | None = None,
    process_path: str | Path | None = None,
    setup_frequency_ghz: float = 6.0,
    sweep_start_ghz: float = 1.0,
    sweep_stop_ghz: float = 12.0,
    sweep_points: int = 221,
    run: bool = False,
    solve: bool = False,
    run_hfss: bool = True,
    run_q3d: bool = True,
) -> dict[str, Any]:
    """Write HFSS/Q3D PyAEDT scripts and optionally execute them."""
    gds = Path(gds_path).resolve()
    config_file = Path(config_path)
    hfss_script = Path(hfss_script_path)
    q3d_script = Path(q3d_script_path)
    report_file = Path(report_path)
    hfss_project = Path(hfss_project_path)
    q3d_project = Path(q3d_project_path)
    stem = hfss_project.with_suffix("")
    outputs = {
        "hfss_project": str(hfss_project.resolve()),
        "q3d_project": str(q3d_project.resolve()),
        "hfss_results_json": str(stem.with_suffix(".hfss.results.json").resolve()),
        "q3d_results_json": str(stem.with_suffix(".q3d.results.json").resolve()),
        "eigenmode_json": str(stem.with_suffix(".eigenmode.json").resolve()),
        "touchstone_s2p": str(stem.with_suffix(".s2p").resolve()),
        "q3d_matrix_csv": str(stem.with_suffix(".q3d.matrix.csv").resolve()),
        "electric_field_png": str(stem.with_suffix(".Efield.png").resolve()),
        "magnetic_field_png": str(stem.with_suffix(".Hfield.png").resolve()),
        "current_density_png": str(stem.with_suffix(".current_density.png").resolve()),
    }
    config = build_pyaedt_config(
        gds,
        outputs=outputs,
        sidecar_path=sidecar_path,
        process_path=process_path,
        setup_frequency_ghz=setup_frequency_ghz,
        sweep_start_ghz=sweep_start_ghz,
        sweep_stop_ghz=sweep_stop_ghz,
        sweep_points=sweep_points,
    )
    config_file.parent.mkdir(parents=True, exist_ok=True)
    config_file.write_text(json.dumps(config, indent=2), encoding="utf-8")
    _write_script(HFSS_SCRIPT, config_file, hfss_script)
    _write_script(Q3D_SCRIPT, config_file, q3d_script)

    result: dict[str, Any] = {
        "schema": "text-to-gds.pyaedt-project.v1",
        "status": "prepared",
        "backend": "Ansys Electronics Desktop through PyAEDT 1.1+",
        "source_gds": str(gds),
        "config_path": str(config_file),
        "hfss_script_path": str(hfss_script),
        "q3d_script_path": str(q3d_script),
        "expected_outputs": outputs,
        "capabilities": [
            "HFSS driven-modal S-parameters",
            "HFSS eigenmode frequency and Q data",
            "HFSS electric, magnetic, and surface-current field images",
            "Q3D Maxwell and coupling capacitance matrices",
        ],
        "review_gates": list(config["validity"].values()),
    }
    if run:
        returncodes = []
        if run_hfss:
            result["hfss_execution"] = _execute_script(hfss_script, solve=solve)
            returncodes.append(result["hfss_execution"]["returncode"])
        if run_q3d:
            result["q3d_execution"] = _execute_script(q3d_script, solve=solve)
            returncodes.append(result["q3d_execution"]["returncode"])
        result["status"] = (
            "executed" if returncodes and all(code == 0 for code in returncodes) else "execution_failed"
        )
    report_file.parent.mkdir(parents=True, exist_ok=True)
    report_file.write_text(json.dumps(result, indent=2), encoding="utf-8")
    result["report_path"] = str(report_file)
    return result


def write_hfss_project_bridge(
    gds_path: str | Path,
    *,
    script_path: str | Path,
    report_path: str | Path,
    project_path: str | Path,
    setup_frequency_ghz: float = 6.0,
    sidecar_path: str | Path | None = None,
    process_path: str | Path | None = None,
) -> dict[str, Any]:
    """Backward-compatible HFSS entry point backed by the full PyAEDT bundle."""
    project = Path(project_path)
    stem = project.with_suffix("")
    return write_pyaedt_project_bundle(
        gds_path,
        config_path=stem.with_suffix(".pyaedt.config.json"),
        hfss_script_path=script_path,
        q3d_script_path=stem.with_suffix(".q3d.py"),
        report_path=report_path,
        hfss_project_path=project,
        q3d_project_path=stem.with_suffix(".q3d.aedt"),
        sidecar_path=sidecar_path,
        process_path=process_path,
        setup_frequency_ghz=setup_frequency_ghz,
    )


def em_geometry_correction(
    *,
    target_frequency_ghz: float,
    extracted_frequency_ghz: float,
    extracted_impedance_ohm: float | None = None,
    target_impedance_ohm: float = 50.0,
) -> dict[str, Any]:
    """Return first-order geometry seeds for the next EM-backed optimization iteration."""
    if target_frequency_ghz <= 0 or extracted_frequency_ghz <= 0:
        raise ValueError("Target and extracted frequencies must be positive")
    frequency_ratio = extracted_frequency_ghz / target_frequency_ghz
    result: dict[str, Any] = {
        "schema": "text-to-gds.em-geometry-correction.v1",
        "target_frequency_ghz": target_frequency_ghz,
        "extracted_frequency_ghz": extracted_frequency_ghz,
        "frequency_error_percent": 100.0
        * (extracted_frequency_ghz - target_frequency_ghz)
        / target_frequency_ghz,
        "recommended_cpw_length_scale": frequency_ratio,
        "recommended_capacitance_scale_if_inductance_fixed": frequency_ratio**2,
        "recommended_inductance_scale_if_capacitance_fixed": frequency_ratio**2,
        "validity": "First-order optimizer seed; rerun HFSS/Q3D after geometry regeneration.",
    }
    if extracted_impedance_ohm is not None:
        if extracted_impedance_ohm <= 0 or target_impedance_ohm <= 0:
            raise ValueError("Extracted and target impedances must be positive")
        result["extracted_impedance_ohm"] = extracted_impedance_ohm
        result["target_impedance_ohm"] = target_impedance_ohm
        result["recommended_cpw_gap_scale_seed"] = math.sqrt(
            target_impedance_ohm / extracted_impedance_ohm
        )
    return result
