"""Strict layout quality-mode system for the fabrication-real CAD pipeline.

This module centralises the decision of *whether a given PCell may be generated*
under a requested quality mode. It exists so the rule lives in one place instead of
being scattered through ``server.py``.

The four modes are deliberately exhaustive:

- ``fabrication_real`` (default): only PCells with a verified fabrication-real
  generator may produce GDS. Anything else returns ``unsupported`` — never a fake or
  toy layout.
- ``reference_import``: the layout is imported from an external reference design
  (KQCircuits / Qiskit Metal) rather than generated by our PCells. ``compile_layout``
  does not generate references; callers must use ``import_reference_layout``.
- ``demo``: explicit opt-in to toy/visualisation-only PCells. Demo PCells *never* run
  unless this mode is requested explicitly.
- ``unsupported``: a terminal classification, not a generation request. Asking to
  generate in this mode is always rejected.

Migration note: ``FABRICATION_REAL_PCELLS`` and ``QUARANTINED_TOY_PCELLS`` previously
lived in ``server.py``. They now live here and are re-exported from ``server`` for
backwards compatibility, so existing imports keep working.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, get_args

LayoutQualityMode = Literal["fabrication_real", "reference_import", "demo", "unsupported"]

VALID_MODES: tuple[LayoutQualityMode, ...] = get_args(LayoutQualityMode)
DEFAULT_MODE: LayoutQualityMode = "fabrication_real"

# PCells with a verified fabrication-real generator (real coplanar gaps, real junction
# overlaps, real via arrays, connected nets, ports, and extraction targets).
FABRICATION_REAL_PCELLS: frozenset[str] = frozenset(
    {
        "cpw_quarter_wave_resonator",
        "cpw_resonator_real",
        "cpw_straight",
        "dc_squid_pair",
        "fabrication_real_cpw_resonator",
        "fabrication_real_dc_squid",
        "fabrication_real_manhattan_jj",
        "lumped_element_jpa_seed",
        "manhattan_jj_real",
        "manhattan_josephson_junction",
        "squid_real",
        "via_chain_real",
    }
)

# Toy/demo/research cells that are deliberately quarantined out of fabrication_real
# mode. The value is the honest reason returned to the caller.
QUARANTINED_TOY_PCELLS: dict[str, str] = {
    "flux_bias_line": "standalone bias-line fragment; no complete device nets, pads, or solver-ready boundary conditions",
    "ground_plane": "ground-only coupon has no etched CPW slots, ports, nets, or extraction target",
    "jj_ic_calibration_array": "calibration array lacks verified per-junction overlap extraction and measurement routing signoff",
    "meander_inductor": "standalone symbolic inductor fragment; not a solver-ready superconducting cell",
    "periodically_loaded_kit_unit_cell": "research/demo unit cell not validated as fabrication-real superconducting layout",
    "photonic_crystal_stwpa": "research/demo TWPA cell not validated as fabrication-real superconducting layout",
    "via_chain_monitor": "via-chain monitor is not yet verified as alternating-layer chain with extracted connectivity",
    "via_stack": "single via fragment; no complete device nets or measurement routing",
}


@dataclass(frozen=True)
class QualityRecord:
    """Intrinsic quality classification of a PCell, independent of requested mode."""

    pcell: str
    layout_quality_mode: LayoutQualityMode
    status: str  # "supported" | "unsupported"
    reason: str | None = None

    def to_dict(self) -> dict[str, str | None]:
        return {
            "pcell": self.pcell,
            "layout_quality_mode": self.layout_quality_mode,
            "status": self.status,
            "reason": self.reason,
        }


@dataclass(frozen=True)
class GateDecision:
    """Result of gating a generation request for a PCell under a requested mode."""

    allowed: bool
    requested_mode: LayoutQualityMode
    record: QualityRecord
    reason: str | None = None

    def to_dict(self) -> dict[str, object]:
        return {
            "allowed": self.allowed,
            "requested_mode": self.requested_mode,
            "record": self.record.to_dict(),
            "reason": self.reason,
        }


def normalize_mode(mode: str) -> LayoutQualityMode:
    """Validate and normalise a requested quality mode.

    ``demo_only`` is accepted as a legacy alias for ``demo``. Anything else not in
    :data:`VALID_MODES` raises ``ValueError`` — strict by design.
    """
    if mode == "demo_only":
        return "demo"
    if mode not in VALID_MODES:
        raise ValueError(
            f"Unknown layout_quality_mode '{mode}'. Valid modes: {list(VALID_MODES)}"
        )
    return mode  # type: ignore[return-value]


def classify_pcell(pcell: str) -> QualityRecord:
    """Return the intrinsic quality classification of *pcell*."""
    if pcell in FABRICATION_REAL_PCELLS:
        return QualityRecord(pcell, "fabrication_real", "supported")
    if pcell in QUARANTINED_TOY_PCELLS:
        return QualityRecord(pcell, "demo", "unsupported", QUARANTINED_TOY_PCELLS[pcell])
    return QualityRecord(
        pcell, "unsupported", "unsupported", "PCell has no fabrication-real quality record"
    )


def gate_generation(pcell: str, requested_mode: str) -> GateDecision:
    """Decide whether *pcell* may be generated under *requested_mode*.

    The matrix:

    ===================  ====================================================
    requested_mode       allowed PCells
    ===================  ====================================================
    fabrication_real     only fabrication-real PCells
    demo                 fabrication-real OR quarantined demo PCells (explicit)
    reference_import     none (callers must use ``import_reference_layout``)
    unsupported          none (terminal classification, never generates)
    ===================  ====================================================
    """
    mode = normalize_mode(requested_mode)
    record = classify_pcell(pcell)

    if mode == "fabrication_real":
        if record.layout_quality_mode == "fabrication_real":
            return GateDecision(True, mode, record)
        reason = record.reason or (
            "PCell is not fabrication-real; request demo mode explicitly to generate a toy layout"
        )
        return GateDecision(False, mode, record, reason)

    if mode == "demo":
        # Explicit opt-in: fabrication-real cells are strictly better, so they pass too.
        if record.layout_quality_mode in ("fabrication_real", "demo"):
            return GateDecision(True, mode, record)
        return GateDecision(False, mode, record, record.reason)

    if mode == "reference_import":
        return GateDecision(
            False,
            mode,
            record,
            "reference_import does not generate PCells; use import_reference_layout()",
        )

    # mode == "unsupported"
    return GateDecision(
        False, mode, record, "'unsupported' is a terminal classification and never generates a layout"
    )
