"""IDC + CPW measurement test structure generator.

Vertical stack (bottom → top): GSG launch pad → CPW feed trace → IDC (device
under test) → CPW feed trace → GSG launch pad, flanked by two continuous
ground planes. The IDC sub-geometry is generated by :class:`IDCGenerator`
itself, so the capacitance-extraction region is byte-identical to a standalone
IDC with the same parameters — that is what makes the documented
"FasterCap extracts the IDC region only" claim checkable.
"""

from __future__ import annotations

from pydantic import BaseModel

from textlayout.generators.idc import IDCGenerator
from textlayout.models import Geometry, Point, Polygon, Port, Technology, rectangle
from textlayout.ports.generator import Generator
from textlayout.research.formulas import cpw_z0
from textlayout.schemas.dsl.idc import IDCSpec
from textlayout.schemas.dsl.test_structure import TestStructureSpec

#: Fixed polygons emitted before the embedded IDC: 2 launch pads, 2 feed
#: traces, 2 ground planes.
_FIXED_POLYGONS_BEFORE_IDC = 6


class TestStructureGenerator(Generator):
    """Generates a two-port IDC measurement structure with CPW launches."""

    name = "TestStructure"
    params_model = TestStructureSpec

    def generate(self, params: BaseModel, tech: Technology, origin: Point) -> Geometry:
        assert isinstance(params, TestStructureSpec)
        x0, y0 = origin
        metal = params.metal_layer

        idc_spec = IDCSpec(
            finger_pairs=params.finger_pairs,
            finger_width_um=params.finger_width_um,
            gap_um=params.gap_um,
            overlap_um=params.overlap_um,
            bus_width_um=params.bus_width_um,
            metal_layer=metal,
        )
        idc_width = (
            2 * params.finger_pairs * params.finger_width_um
            + (2 * params.finger_pairs - 1) * params.gap_um
        )
        cx = x0 + max(idc_width, params.launch_width_um) / 2.0 + params.ground_clearance_um

        launch_lo = y0
        feed_lo = launch_lo + params.launch_length_um
        idc_lo = feed_lo + params.feed_length_um
        idc = IDCGenerator().generate(idc_spec, tech, (cx - idc_width / 2.0, idc_lo))
        idc_height = float(idc.metadata["total_height_um"])
        idc_hi = idc_lo + idc_height
        feed_hi_end = idc_hi + params.feed_length_um
        launch_hi_end = feed_hi_end + params.launch_length_um

        half_launch = params.launch_width_um / 2.0
        half_feed = params.feed_width_um / 2.0
        signal_half = max(idc_width / 2.0, half_launch)
        ground_inner = signal_half + params.ground_clearance_um

        # A 1 µm overlap guarantees electrical continuity between abutting
        # rectangles regardless of downstream boolean handling of shared edges.
        seam = 1.0
        fixed: tuple[Polygon, ...] = (
            rectangle(metal, cx - half_launch, launch_lo, cx + half_launch, feed_lo + seam),
            rectangle(metal, cx - half_launch, feed_hi_end - seam, cx + half_launch, launch_hi_end),
            rectangle(metal, cx - half_feed, feed_lo, cx + half_feed, idc_lo + seam),
            rectangle(metal, cx - half_feed, idc_hi - seam, cx + half_feed, feed_hi_end),
            rectangle(
                metal,
                cx - ground_inner - params.ground_width_um,
                launch_lo,
                cx - ground_inner,
                launch_hi_end,
            ),
            rectangle(
                metal,
                cx + ground_inner,
                launch_lo,
                cx + ground_inner + params.ground_width_um,
                launch_hi_end,
            ),
        )
        polygons = (*fixed, *idc.polygons)

        ports = (
            Port("P1", (cx, launch_lo), params.launch_width_um, 270.0, metal),
            Port("P2", (cx, launch_hi_end), params.launch_width_um, 90.0, metal),
            Port(
                "GND_L",
                (cx - ground_inner - params.ground_width_um / 2.0, launch_lo),
                params.ground_width_um,
                270.0,
                metal,
            ),
            Port(
                "GND_R",
                (cx + ground_inner + params.ground_width_um / 2.0, launch_lo),
                params.ground_width_um,
                270.0,
                metal,
            ),
        )

        z0, eps_eff = cpw_z0(params.feed_width_um, params.feed_gap_um, tech.substrate_epsilon_r)
        return Geometry(
            name="TestStructure",
            polygons=polygons,
            ports=ports,
            metadata={
                "component": "TestStructure",
                "metal_layer": metal,
                "min_ports": 4,
                "device_under_test": "IDC",
                "estimated_capacitance_pf": idc.metadata["estimated_capacitance_pf"],
                "capacitance_method": idc.metadata["capacitance_method"],
                "feed_estimated_z0_ohm": round(z0, 4),
                "feed_effective_permittivity": round(eps_eff, 4),
                "analytical_estimate": True,
                "analytical_quantity": "capacitance",
                # Extraction contract: FasterCap sees ONLY the embedded IDC.
                "extraction_region": {
                    "component": "IDC",
                    "polygon_start": _FIXED_POLYGONS_BEFORE_IDC,
                    "polygon_count": len(idc.polygons),
                    "parameters": idc_spec.model_dump(mode="json"),
                    "origin": [cx - idc_width / 2.0, idc_lo],
                    "excluded": "launch pads, feed traces, and ground planes are NOT simulated",
                },
                "total_width_um": round(2 * (ground_inner + params.ground_width_um), 4),
                "total_height_um": round(launch_hi_end - launch_lo, 4),
                "idc": dict(idc.metadata),
            },
        )
